### ISSUE TITLE
CSS Template

### ISSUE THREAD

**Issue by jonathanrdelgado** [twolfson/gulp.spritesmith#1]
Would you be opposed to a PR that added an option to utilize `json2css.addMustacheTemplate`?

We have a retina sprite that requires some special options.

**Comment by twolfson** [comment]
As a heads up, `gulp.spritesmith@3.5.0` now supports retina spritesheets. More information can be found here:

https://github.com/twolfson/gulp.spritesmith#retina-parameters

https://github.com/twolfson/gulp.spritesmith#retina-spritesheet
