### ISSUE TITLE
Spritesmith not generating retina mixins

### ISSUE THREAD

**Issue by quakes** [twolfson/gulp.spritesmith#100]
Hi, I was working with spritesmith and realized that it wasn't generating any of the retina mixins.

After fiddling around, I found that the when you include the `cssFormat` option, the retina mixins don't get generated.

Thanks for a great plugin.

**Comment by twolfson** [comment]
To get retina information generated (e.g. spritesheet, variables), please follow the retina documentation in the README. `cssFormat` works but isn't the preferred venue

https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#retina-parameters
