### ISSUE TITLE
Change Retina Media Rule

### ISSUE THREAD

**Issue by theyuv** [twolfson/gulp.spritesmith#101]
Hello,

I'm not using LESS or a custom template.

Is there any way to change the media rule that is used for the retina sprite?

I would like something like:
```
@media only screen and (-webkit-min-device-pixel-ratio: 2), 
       only screen and (min--moz-device-pixel-ratio: 2),   
       only screen and (min-resolution: 2dppx),             
       only screen and (min-resolution: 192dpi)  
```           
(according to this page's recommendation: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#-moz-device-pixel-ratio)

For example, to customize my other rules I just use `cssOpts: cssSelector: function(item)` and run a custom js function using `item.name`.

Is there something similar I can do to manipulate the retina media query?

Thanks

**Comment by twolfson** [comment]
For what it's worth, the content you linked to mentions that as an example (not best practice). `min--moz-device-pixel-ratio` is only for Firefox < 15, and `2dppx` is redundant to `192dpi` (i.e. any modern browser that supports `2dppx` will support `192dpi` and they are equivalent measures -- https://developer.mozilla.org/en-US/docs/Web/CSS/resolution).

That being said, here's how you would accomplish what you want:

# Text replacement
The super simplest way would be to have another `gulp` task replace the media query content:

https://www.npmjs.com/package/gulp-replace/

```js
// Generate our spritesheet
var spriteData = gulp.src('images/*.png').pipe(spritesmith({
  imgName: 'sprite.png',
  cssName: 'sprite.css'
}));

// Pipe CSS stream through string replacement and onto disk
var originalMediaQuery = [
  '@media (-webkit-min-device-pixel-ratio: 2),'
  '       (min-resolution: 192dpi)'
].join('\n');
var newMediaQuery = [
  '@media only screen and (-webkit-min-device-pixel-ratio: 2),',
  '       only screen and (min--moz-device-pixel-ratio: 2),',
  '       only screen and (min-resolution: 2dppx),',
  '       only screen and (min-resolution: 192dpi)'
].join('\n');
var cssStream = spriteData.css
  .pipe(replace(originalMediaQuery, newMediaQuery))
  .pipe(gulp.dest('path/to/css/folder/'));
```

# Custom template
A custom CSS template can be used that's based on our existing retina CSS template. Here's a link to the documentation and original templates:

https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#templating

https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/css_retina.template.handlebars

https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/css_retina.template.js

**Comment by theyuv** [comment]
Thank you very much.

I see on the css-tricks page that you linked in the documentation that my media query is outdated...it's just what I see done on a lot of other applications and plugins.  I will look into it further and see if it's necessary.

Thank you.

**Comment by theyuv** [comment]
Testing reply from email
