### ISSUE TITLE
only retina version

### ISSUE THREAD

**Issue by stephanedemotte** [twolfson/gulp.spritesmith#104]
Can we have only retina version for all screens ?

Don't need the normal version.

With this config
```
    retinaSrcFilter: [paths.src + '/*.png'],
    retinaImgName: 'sprite.png',
```
I got this error
```
Retina settings detected but 1 retina images were found. We have 0 normal images and expect these numbers to line up. Please double check `retinaSrcFilter`
```

thank you !

**Comment by stephanedemotte** [comment]
simple hack in stylus
```
$spritesheet_width = $spritesheet_width / 2
$spritesheet_height = $spritesheet_height / 2

spriteWidth($sprite) {
  width: ($sprite[4] / 2)
}

spriteHeight($sprite) {
  height: ($sprite[5] / 2)
}

spritePosition($sprite) {
  background-position: ($sprite[2] / 2) ($sprite[3] / 2);
  background-size: $spritesheet_width $spritesheet_height;
}
```

But maybe there are a better way ?

**Comment by twolfson** [comment]
The simplest approach would be to treat the retina sprites as a normal spritesheet and override the `sprite` mixin to also define `background-size` at half-width and half-height:

**spritesmith task:**

```js
gulp.src(paths.src + '/*.png').pipe(spritesmith({
  imgName: 'sprite.png',
  cssName: 'sprite-auto.styl'
}));
```

**Stylus content:**

```stylus
// Import spritesmith variables and mixins 
@import "sprite-auto"

// Define `spriteHalfBackgroundSize` mixin which downsizes retina spritesheets
// https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/stylus_retina.template.handlebars#L57-L71
spriteHalfBackgroundSize($sprite) {
  background-size: ($sprite[6] / 2) ($sprite[7] / 2);
}

// Override `sprite` mixin to use `spriteHalfBackgroundSize`
// https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/stylus.template.handlebars#L93-L98
sprite($sprite) {
  spriteImage($sprite)
  spritePosition($sprite)
  spriteWidth($sprite)
  spriteHeight($sprite)
  spriteHalfBackgroundSize($sprite)
}
```

**Comment by stephanedemotte** [comment]
don't need to set the sprite width and the position ?

I have try your code, but don't work as expected :)

**Comment by twolfson** [comment]
The sprite width and position are set by the `spriteWidth` and `spritePosition` mixins which are being invoked. The example above was written without testing so it's possible something is wrong but the gist is there (i.e. override the `sprite` mixin in Stylus with the new properties)

**Comment by howeller** [comment]
Are you overwriting the `sprite` mixin in` stylus.template.handlebars`? Or making a new file to override? Any help would be appreciated as I'd love to get this feature working as well.
Thanks!
