### ISSUE TITLE
Can I have 2 sprites?

### ISSUE THREAD

**Issue by JuliaRietveld25** [twolfson/gulp.spritesmith#105]
Hi Todd,
thanks for this very useful gulpfile.I wonder if it's possible to use some kind of namespacing of a prefix for $stylesheet and $sprite variables. I need to generate 2 sprites in my project. They produce the same scss variable names and break my styling.
Any ideas?
Thank you in advance,

Julia from The Netherlands

**Comment by twolfson** [comment]
Namespacing can be done via the `cssVarMap` option. See the README documentation for example usage:

https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#variable-mapping
