### ISSUE TITLE
gulp-sass-lint throws a few errors unless I relax sass.lint-yml rules

### ISSUE THREAD

**Issue by tstermitz** [twolfson/gulp.spritesmith#106]
When spritesmith generates a sprite.scss file, my sass.lint-yml file complains about:
 - error  No unit allowed for values of 0  zero-unit
 - error  Quotes around URLs are required  url-quotes
 - error  Space expected between blocks    empty-line-between-blocks

At this point you can't turn off listing for specific directories, although you can change the errors to warnings. I'd prefer to keep my syntax fairly strict.

**Comment by twolfson** [comment]
The code generated from `gulp.spritesmith` should be considered to be external code (e.g. code you get from `bower`, `npm`). As a result, it shouldn't be linted (which I think you are aware of). It looks like `gulp-sass-lint` uses `gulp.src` so we should be able to filter out the file from there:

https://github.com/sasstools/gulp-sass-lint/tree/v1.2.0#usage

https://github.com/gulpjs/gulp/blob/v3.9.1/docs/API.md#gulpsrcglobs-options

https://github.com/isaacs/node-glob/tree/v7.1.1#glob-primer

```js
// Load and lint all SCSS files except content generated by spritesmith
gulp.src(['path/to/*.scss', '!path/to/sprite.scss'])
  .pipe(gulpSassLint())
  // ...
```
