### ISSUE TITLE
Enhancement: optional JSON output

### ISSUE THREAD

**Issue by CramericaIndustries** [twolfson/gulp.spritesmith#107]
An option to get the sprite information (position, size, filename) in shape of a javascript object/array would be very handy.
Background: I'm using gulp and spritesmith (not gulp.spritesmith) to generate a sprite which I'm not using in a HTML website. Therefore I can't use the generated CSS file. I'm putting together a JSON array that contains all the info needed to use the sprite:
```
[{
  "fileName": "xyz.png"
 ,"x": 10
 ,"y": 10
 ,"w": 200
 ,"h": 150
},{...}]
```

**Comment by CramericaIndustries** [comment]
Ah sorry, now I feel embarrassed! Moments after I submitted my feature request I found the gulp.spritesmith `cssName: "xyz.json"` option, which does exactly what I need (JSON output instead of CSS).
Sorry again!

**Comment by twolfson** [comment]
It looks like you actually want the `json_array` format (array of objects) instead of the `json` format (object, keyed by sprite name). To opt into that, use the `cssFormat` option:

```js
cssName: 'xyz.json',
cssFormat: 'json_array'
```

https://github.com/twolfson/spritesheet-templates/tree/10.1.4#json_array
