### ISSUE TITLE
Better retina sprite generation support

### ISSUE THREAD

**Issue by hisnameisjimmy** [twolfson/gulp.spritesmith#11]
This could easily be the best tool for the job if it just automatically handled some things with retina sprite generation. Right now if I want to use this tool for sprite generation, I have to include another package to resize and rename the resulting image so that I end up with two images, one for regular display and one for retina/hi-dpi. I then have to modify the resulting CSS so that it only shows the retina sprite on retina displays.

[Css-sprite](https://github.com/aslansky/css-sprite) does a much better job of this, automatically generating both images from @2x assets, then creating css that accounts for hi-dpi screens. This means I can watch the folder with my source images, update an image, and have my css and sprites updated without intervention on my part. It's a beautiful thing.

However! Css-sprite doesn't allow for binary-tree packing. This is especially a problem on iOS devices where there are image size limits. These image size limits cause issues with sprites generated in a vertical or horizontal orientation. You can see an example of this here: http://weedygarden.net/demos/hi-res-retina-sprites/ and an explanation of the size issues here: http://weedygarden.net/2012/04/hi-res-retina-display-css-sprites/

**Comment by twolfson** [comment]
As a heads up, `gulp.spritesmith@3.5.0` now supports retina spritesheets. More information can be found here:

https://github.com/twolfson/gulp.spritesmith#retina-parameters

https://github.com/twolfson/gulp.spritesmith#retina-spritesheet
