### ISSUE TITLE
How to delete icon prefix?

### ISSUE THREAD

**Issue by rorc** [twolfson/gulp.spritesmith#110]

**Comment by twolfson** [comment]
The `icon-` prefix in the CSS template can be removed via `cssOpts.cssSelector`:

```js
spritesmith({
  imgName: 'sprite.png',
  cssName: 'sprite.css',
  cssOpts: {
    // Return sprite name as a class selector
    cssSelector: function (sprite) { return '.' + sprite.name; }
  }
})
```

https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#documentation

https://github.com/twolfson/spritesheet-templates/tree/10.1.4#css

**Comment by rorc** [comment]
Ok, thanks :)
