### ISSUE TITLE
can I get the size of the output sprite image?

### ISSUE THREAD

**Issue by anrananran** [twolfson/gulp.spritesmith#117]
is there any way to get the size of the output sprite image?

**Comment by twolfson** [comment]
Yes, it's provided as the "total width" and "total height" variables on each sprite as well as the spritesheet "width" and "height" variables. Here is relevant documentation and examples:

https://github.com/twolfson/gulp.spritesmith/tree/6.4.0#templating

https://github.com/twolfson/spritesheet-templates/blob/10.2.1/test/expected_files/scss.scss#L41-L42

https://github.com/twolfson/spritesheet-templates/blob/10.2.1/test/expected_files/scss.scss#L45-L46

**Comment by anrananran** [comment]
OK, Thanks a lot ! I will read the documentation more carefully
