### ISSUE TITLE
Separate destination folder image and css

### ISSUE THREAD

**Issue by myurtsev** [twolfson/gulp.spritesmith#119]
Hi, I was wondering how I can set a different destination folder for the generated image and the css. Now they are both in the same folder. Ty!

**Comment by twolfson** [comment]
Separate folders can be managed by using the separate image and CSS
streams. See the "Continuing the pipeline" example in the README as an
example. You won't need the buffer and optimization streams, only the split
dests:

https://github.com/twolfson/gulp.spritesmith/tree/6.4.0#continuing-the-pipeline
