### ISSUE TITLE
Retina Sprites

### ISSUE THREAD

**Issue by rrbiten** [twolfson/gulp.spritesmith#12]
I've tried some tools to build sprites and yours is the best for what I need.

The only thing I'm missing is an option for generating retina sprites. I'd like to know if this is possible with this module and if not, in your opinion, what would be the best approach to work with retina sprites using gulp.

It would be perfect to have an boolean option that would consider all images on a folder to be retina sprites to generate them and then cut their sizes on halt and generate the non-retina sprites.

Another approach is using the @2 which would be ok too... Thanks a lot!

**Comment by twolfson** [comment]
As a heads up, `gulp.spritesmith@3.5.0` now supports retina spritesheets. More information can be found here:

https://github.com/twolfson/gulp.spritesmith#retina-parameters

https://github.com/twolfson/gulp.spritesmith#retina-spritesheet
