### ISSUE TITLE
Unable to create Normal Sprite and Retina Sprite together even when result shows 1 retina image found

### ISSUE THREAD

**Issue by ankamsarav** [twolfson/gulp.spritesmith#127]
I wanted to have both normal sprite and retina sprite. I followed the code in the below URL. I added 1 retina image for testing and getting this error. 
My task
 ```
gulp.task('sprites', function() {
    var spriteData = gulp.src(mysrc + './cartridge/sprites/*.{png,jpg}')
        .pipe(spritesmith({
            padding: 20,
            imgPath: '../images/sprite.png',
            retinaSrcFilter: mysrc + './cartridge/sprites/*@2x.png',
            imgName: 'sprite.png',
            retinaImgName: 'sprite@2x.png',
            cssName: '_sprite.scss'
        }));
    return spriteData.pipe(gulpif('*.png', gulp.dest(mysrc + './cartridge/static/default/images/'), gulp.dest(mysrc + './cartridge/scss/')));
```

**Error:** Retina settings detected but 1 retina images were found. We have 38 normal images and expect these numbers to line up. Please double check `retinaSrcFilter`. 

https://github.com/twolfson/gulp.spritesmith/blob/master/docs/gulpfile.js

**Comment by twolfson** [comment]
The error means that the input files from `gulp.src` cannot be split into equivalent normal and retina sprite sets by filtering against `retinaSrcFilter`. Maybe the `retinaSrcFilter` should include a similar `jpg` expansion?

```js
           retinaSrcFilter: mysrc + './cartridge/sprites/*@2x.{png,jpg}',
```

**Comment by ankamsarav** [comment]
Tried it but know luck. Actually I forgot to mention that I have only 2-3 retina images which needs retina sprite out of a bunch.

**Comment by twolfson** [comment]
To optimize repeated CSS (i.e. reused `background-position), we need to generate normal and retina spritesheets with the same layout. As a result, we need all sprites to be normal/retina to generate these 2 spritesheets concurrently.

One workaround would be to have a separate task for a normal spritesheet and retina spritesheet, then manually define the retina rules for the 2-3 retina sprites.

Is there any reason there are only 2-3 out of 38 sprites that support retina?
