### ISSUE TITLE
png file with size of 0 bytes

### ISSUE THREAD

**Issue by Nubtehy** [twolfson/gulp.spritesmith#131]
I've faced situation when 'sprite' process hangs out and did not create any css file in the project. In sprite folder I have found a png file with size of 0 bytes. When I removed that file, everything started to work. It will be great to throw some notification in this situation.

**Comment by twolfson** [comment]
Ah, nice catch! What was the engine you were using? (e.g. default, `phantomjssmith`, `canvassmith`)

**Comment by Nubtehy** [comment]
I have not installed any custom engine. So it seems that I am using default.

**Comment by twolfson** [comment]
I've reproduced the issue and added a fix in `pixelsmith@2.1.2`. Thanks again for the issue!
