### ISSUE TITLE
SASS generation when image begins with number

### ISSUE THREAD

**Issue by kyranjamie** [twolfson/gulp.spritesmith#132]
Bumped into an issue with the stylesheet generator in the case where an image's name begins with a number.

Couldn't find a ref to this in the sass spec, but sass variables must not begin with a number.  Thus, this code doesn't compile:

```sass
$1st-name: '1st';
$1st-x: 32px;
...
```

Perhaps the handlebar template could contain a prefix?

**Comment by twolfson** [comment]
There are a few options to resolve the issue:

- Rename the images (e.g. 1st to first)
- Use `cssVarMap`
    - https://github.com/twolfson/gulp.spritesmith/tree/6.5.1#variable-mapping
    - The following example will rename `1st-*` to `sprite-1st-*`
      ```js
      cssVarMap: function (sprite) {
        return 'sprite-' + sprite.name;
      }
      ```
- Define a custom template (likely overkill)
    - https://github.com/twolfson/gulp.spritesmith/tree/6.5.1#templating
