### ISSUE TITLE
retina.escaped_image is not including the path the path.

### ISSUE THREAD

**Issue by Trost123** [twolfson/gulp.spritesmith#134]
For example, escaped_image returns ../images/sp-preloader.png, but retina.escaped_image returns sp-preloader@2x.png. For some reason the ../images/ is dropped for retina url.

**Comment by twolfson** [comment]
Are you using any parameters like `imgPath` or `cssSpritesheetName`? If so, can you verify those have equivalent retina parameters set (e.g. `retinaImgPath`)? If that doesn't fix the problem, can you paste your `gulp.spritesmith` configuration?

**Comment by Trost123** [comment]
Oops, sorry 😅 
Yeah, I did a typo and set imgPath two times, instead of setting retinaImgPath.

**Comment by twolfson** [comment]
Cool, glad to hear it was an easy fix =) Ideally we would only have to set that parameter once but I think I initially was targeting flexibility instead of ease of use =/
