### ISSUE TITLE
transition

### ISSUE THREAD

**Issue by yilingsj** [twolfson/gulp.spritesmith#140]
Can the order of the images be arranged according to the order of the picture names? Because of the animation to make slides, the current animation is not perfect.
eg:http://t.cn/Rr8DrXi  
eg2:http://t.cn/Rr8kUPT ,
The animation of the sina icon is correct and qq is incorrect because there is one more icon between the qq icons.

合成图片时的顺序能否根据图片名顺序排列？因为要做滑过的动画，目前的动画不完美。
 sina图标的动画是正确的，qq的不正确，因为qq图标间多一个图标。

**Comment by twolfson** [comment]
Unfortunately, the `binary-tree` layout doesn't offer much in terms of sorting. There are a couple options here:

- Switch to the left/right or top/down layout algorithms
    - https://github.com/twolfson/gulp.spritesmith/tree/6.9.0#algorithms
- Provide a custom layout algorithm and use that
