### ISSUE TITLE
gulp-If. How to check if js file contains specific property?

### ISSUE THREAD

**Issue by junaidahmed92** [twolfson/gulp.spritesmith#141]
I am using gulp.js. But I want to add a condition that if request.debug = true; in any of my js file then gulp task should fail. I have found gulp-if and gulp-fail that I can use for this purpose but I don't know that how can I check the specific condition? Thanks

**Comment by twolfson** [comment]
I don't understand the question. Is this about `gulp.spritesmith` or `gulp` in general?

**Comment by junaidahmed92** [comment]
@twolfson , it's about gulp in general. Like I want to see if any of my js file contains specific string then I just want to fail gulp task

**Comment by twolfson** [comment]
Sorry, I've never dealt with this scenario before so I don't have any ideas off the top of my head. Since this is off topic from `gulp.spritesmith`, I'm going to close this issue as a `wontfix`

I recommend you look at `gulp`, `gulp-if`, `gulp-fail` issue pages as well as searching StackOverflow
