### ISSUE TITLE
 Assembly of a sprite file with a limit on the weight of the sprite file

### ISSUE THREAD

**Issue by GurovDmitriy** [twolfson/gulp.spritesmith#157]
how to supplement your program to collect sprites weighing no more than 200-300kb. Thank you!

we collect banners with your tool. The task is that when, let's say, the fire is animated with a sprite, you need to collect several sprite files from 100 pictures up to 200-300kb ...

**Comment by twolfson** [comment]
Unfortunately, I consider this is outside the scope of `spritesmith`. We try to avoid doing too much (e.g. optimizing images) which can largely swing the results of this

And if we were just to go off of the size of the input sprites, then we can likely find a library to chunk those up for us as well

Thus, outside the scope of `spritesmith`/`gulp.spritesmith`

Closing was `wontfix`
