### ISSUE TITLE
npm warn deprecated 

### ISSUE THREAD

**Issue by MyNameTony1000** [twolfson/gulp.spritesmith#160]
`npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

`npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

npm ls core-js outputs:

```
-- gulp.spritesmith@6.13.1
  -- spritesmith@3.4.1
    -- pixelsmith@2.4.1
      -- get-pixels@3.3.3
        -- request@2.88.2
```
```
-- gulp.spritesmith@6.13.1
  -- spritesmith@3.4.1
    -- pixelsmith@2.4.1
      -- get-pixels@3.3.3
        -- request@2.88.2
          -- uuid@3.4.0
```

How can I fix this moment?

**Comment by twolfson** [comment]
This is a longstanding issue in `get-pixels`, so we have to get a fix there:

https://github.com/scijs/get-pixels/issues/62

https://github.com/scijs/get-pixels/pull/67

Alternatively, we could find a replacement library, but that seems like a lot of effort for something that's already patched

Is this causing you any issues besides the warnings?

**Comment by MyNameTony1000** [comment]
Hello, thanks for the quick response) This does not cause any problems and everything works fine. Just wanted to know if there is a way to fix this.
