### ISSUE TITLE
imgPath doesn't seem to do anything?

### ISSUE THREAD

**Issue by StoneCypher** [twolfson/gulp.spritesmith#21]
There's a parameter `imgPath` which is supposed to allow you to modify the path written into the CSS on output.  Changing it doesn't appear to cause any difference.

It looks like the only place it's used is [here](https://github.com/twolfson/gulp.spritesmith/blob/master/lib/gulp-spritesmith.js#L125), to set the `spritePath` variable, which in turn is only used [here](https://github.com/twolfson/gulp.spritesmith/blob/master/lib/gulp-spritesmith.js#L147), to set the `.image` property of coords, which I think I must be misreading, because [this](https://preview.npmjs.com/package/spritesmith) seems to suggest that that's meant to carry a binary representation of the image itself, rather than a path.

Am I missing something?

**Comment by rsids** [comment]
When using scss as output format, the imgPath is ignored. When using .css as output, the imgPath works as aspected.
