### ISSUE TITLE
Error on npm install, wrong version on npm

### ISSUE THREAD

**Issue by mdunisch** [twolfson/gulp.spritesmith#24]
1.) Error on install

While doing npm install I get this:

```
> canvas@1.1.6 install /PROJEKTNAME/node_modules/gulp-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /PROJEKTNAME/node_modules/gulp-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

Maybe duplicate of https://github.com/Automattic/node-canvas/issues/415?

2.) Wrong version on npm
npm has 0.0.2 as current version (see https://www.npmjs.com/package/gulp-spritesmith)

**Comment by twolfson** [comment]
It looks like you are installing the wrong package. This one is `gulp.spritesmith`:

```bash
npm install gulp.spritesmith
```

`gulp-spritesmith` can be found here:

https://github.com/otouto/gulp-spritesmith

I opened an issue when we both released at the same time but the author hasn't budged on his request for an unnecessary feature.

https://github.com/Otouto/gulp-spritesmith/issues/3

**Comment by mdunisch** [comment]
Thank you for that quick help!

I see that we had "gulp.spritesmith": "^1.4.0", in our packages.json - i updated to 2.4.0 and now i can install it!
