### ISSUE TITLE
Generated Sprite Image file hash

### ISSUE THREAD

**Issue by Romanx** [twolfson/gulp.spritesmith#26]
Hello, It would be extremely useful if at the same time as running spritesmith you could hash the created sprite image and provide the hash as an argument to the cssTemplate in the params object.

This will help when you want to bust the CSS in your CDN when your output sprite file has changed.

**Comment by twolfson** [comment]
This has been discussed in `grunt-spritesmith` in Ensighten/spritesmith#37, Ensighten/grunt-spritesmith#71, Ensighten/grunt-spritesmith#71, and Ensighten/grunt-spritesmith#75.

We are currently deferring this responsibility to another task because it breaks the one thing well principle and is a complex action itself (e.g. multiple algorithms, `md5`, `sha1`, timestamp; additional timing logic/maintenance).

Here are some tasks that can be chained with `spritesmith` to add cache busting:

https://www.npmjs.com/package/gulp-css-urlversion/

https://www.npmjs.com/package/gulp-rev/

**Comment by Romanx** [comment]
Sorry i hadn't seen those previous issues I should have looked more diligently. I can't seem to find any use-cases for using gulp-rev with spritesmith. 

I understand you could chain it into the img stream to change the output file to contain a content hash but that would cause the image name to be incorrect in the generated css. 

I'm assuming your solution would be to use the generated manifest to replace the image urls with the changed file names?

If you could provide any examples that would be very helpful,

Thanks

**Comment by twolfson** [comment]
The most straightforward approach would be to define this as a separate task in your pipeline:

```js
// Define our spritesmith task
gulp.task('sprite', function () {
  var spriteData = gulp.src('images/*.png').pipe(spritesmith({
    imgName: 'sprite.png',
    cssName: 'sprite.css'
  }));
  spriteData.pipe(gulp.dest('tmp/'));
});

// Define our cache busting task which depends on the `sprite` task (meaning they run in series)
gulp.task('cache-bust', ['sprite'], function () {
    return gulp.src('tmp/*.css')
        .pipe(rev())
        .pipe(gulp.dest('dist/'));
});
```

Alternatively, you can define these in the same task but then you need to wait for your output pipe to close.

```js
gulp.task('sprite', function (done) {
  // Output our sprites
  var spriteData = gulp.src('images/*.png').pipe(spritesmith({
    imgName: 'sprite.png',
    cssName: 'sprite.css'
  }));
  var fsPipe = spriteData.pipe(gulp.dest('tmp/'));

  // When we are done writing our CSS and images to disk, run our cache buster
  fsPipe.on('finish', function () {
    gulp.src('tmp/*.css')
        .pipe(rev())
        .pipe(gulp.dest('dist/'))
        .on('finish', done);
  });
});
```

**Comment by Romanx** [comment]
Looking at those examples that's going to version only the CSS from  ```"tmp/mySprite.css" ``` to ```"dest/mySprite-098f6bcd.css"``` for example.

What we'd like would be to version the sprite being produced by hashing the produced content in the buffer. 

This can't be done after spritesmith without using a temporary file for the sprite, rev-ing the generated sprite image, generating the manifest, saving it and then using another library to find and replace all usages of the original sprite name with the new name using the generated manifest and then saving the new version.

The alternate to this would be the suggested solution of generating a simple hash from the sprite file buffer and adding it to the stylesheet params. This would keep the plugin doing exactly what it's doing now but with a parameter simply being added to the params which get passed in to the template. 

This way you could easily use it for a query string busting inside the CSS to avoid the six steps above. If you wouldn't be against the idea i'd be willing to try write a quick implementation in a fork so that we could discuss it?

**Comment by twolfson** [comment]
It looks like I misunderstood your initial issue. My opinion remains the same; the renaming action can be done a lot of ways (e.g. `md5`, `sha1`, timestamp) and should be isolated in its own task, focusing on one thing well.

The benefit of it being treated as its own `gulp` task would be reusable by other build chains, not only `gulp.spritesmith` images (e.g. a font build task, renaming CSS/JS filenames for their HTML references).

I would envision an API like:

```js
gulp
  .src('*.{css,png}')
  // Cache-bust any local files references in CSS URL's
  //   Internally, it catches any CSS files and waits for all local files to be streamed in
  //   If not found by the end of the stream, it complains and emits an error
  //   Otherwise, it renames the PNG file (e.g. `gulp-rename`) and adjusts the CSS content with our PNG
  .pipe(cachebuster.cssUrl())
  // Output adjusted files
  .pipe('dest/');
```

For `gulp.spritesmith`, this would be leveraged in the pipe to not lose memory (which seems to be your concern)

```js
gulp.task('sprite', function () {
  gulp
    .src('images/*.png')
    .pipe(spritesmith({
      imgName: 'sprite.png',
      cssName: 'sprite.css'
    }))
    .pipe(cachebuster.cssUrl())
    .pipe(gulp.dest('tmp/'));
});
```

**Comment by borys-p** [comment]
Adding a cache-busting directly to the spritesmith would make code much more readable. I just finished implementing a cache-busting technique similar to Compass, where image name has an unique suffix added, based on file contents. And the resulting code is... awful. I had to use promises, closures and a lot of unnecessary code, because you have to process images first (get the contents, calculate hashes), wait for the images to finish processing (to have all hashes), compile merged sass streams and update file paths in the resulting file. 80 lines, which could be shortened to an extra option, because inside spritesmith you have everything already available (image contents and file paths). Modyfying it afterwards is one big ugly hack.

You mentioned mutiple alghoritms (md5, sha1, etc.) - it doesn't matter which one you use. You need only to change the hash when file contents change. And you don't need the full hash, 8 first characters will be unique enough.

**Comment by twolfson** [comment]
@borys-p I believe there's a conflation between detecting a `gulp` task's input has changed and cache busting for the browser.

For caching a `gulp` task itself (i.e. don't regenerate spritesheet if nothing has changed), we can use existing libraries like:

https://www.npmjs.com/package/gulp-diff-build/

which can be reused with other tasks (e.g. HTML, CSS, JS generation).

For cache busting in the browser, we don't care about the input items -- only the resulting images and CSS. For example, if the name of a sprite changed but its contents didn't, then we still might generate the same image and thus have the same hash of the final spritesheet. That was the focus of this issue and we believe it's reusable enough that it should be built as a separate library

**Comment by Romanx** [comment]
I actually went a different route with my solution to this problem as suggested by @twolfson I wrote https://www.npmjs.com/package/gulp-spritesmash and https://www.npmjs.com/package/gulp-hydra which takes the output of spritesmith, revs and versions the files and references in the pipe and then split the output into the same form again as spritesmith. That way we could have the same interface with revision and without.

Neither have been actively updated to play nicely with newer version of spritesmith but they should still work, if they don't feel free to open an issue for them.

**Comment by borys-p** [comment]
@Romanx why I didn't find your plugin earlier... 
Maybe there should be a separate section in spritesmith's documentation with recommended packages? It could stop some people from reinventing the wheel.

@twolfson I'm not sure if I understand you correctly. Diff-build is a nice addition to the process, but you still need a way to force the browser to download updated files by changing their names. And you have already everything to do it inside of spritesmith. Doing it with output streams requires [a lot of magic](https://github.com/MasterOfMalt/gulp-spritesmash/blob/master/src/index.js).

**Comment by Romanx** [comment]
@borys-p I'd be happy to have spritesmash added to some kind of _extensions_ section @twolfson what do you think about that idea?

**Comment by twolfson** [comment]
@borys-p @Romanx I'm happy to add it as an extension via documentation. Can someone verify that it works with the latest `gulp.spritesmith`?

**Comment by Romanx** [comment]
@twolfson I've just tested and updated spritesmash with the newest version. The change in returning streams and not buffering was the only pain. Added in some switching logic to buffer up the streams internally to hash the files. There's probably a better way of doing it but i'll be damned if I know it.

**Comment by twolfson** [comment]
@Romanx Ah, my mind skipped on that being necessary. We suggest people use `vinyl-buffer` before passing the `spritesmith` output to something that requires the full image (e.g. `imagemin`):

https://github.com/twolfson/gulp.spritesmith/tree/6.5.0#continuing-the-pipeline

To concatenate content itself in a library (not recommended in this `gulp` scenario), I'd suggest using `concat-stream`:

https://github.com/maxogden/concat-stream

Let me know if you consider it good to be added as documentation

**Comment by Romanx** [comment]
@twolfson Buffer is how I know to do it too, and that's what i'd recommend. I'll update the readme to show using buffer, it'll work with native streaming it just won't be optimal. I'm happy to consider it good enough to be added in the docs.

**Comment by twolfson** [comment]
Cool, I'll whip something up and post here when I'm done

**Comment by twolfson** [comment]
Alright, I've documented cache busting/`spritesmash` in the examples section and released it in 6.5.1:

https://github.com/twolfson/gulp.spritesmith/tree/6.5.1#cache-busting

Fwiw, our documentation is getting long in the teeth and an "Extensions" sections jammed in the noise didn't feel quite right. I will prob consolidate, website-ify, and break it down some day although I've been uncertain of how much longer people will want spritesheets for (e.g. SVGs and HTTP 2.0 are gaining traction)

Thanks a bunch for your work @Romanx!

**Comment by borys-p** [comment]
@twolfson Don't worry. HTTP/2 is still a PITA, SVGs are almost impossible to use as sprites properly with caching (Safari still doesn't support fragment identifiers in external images) and we have to support older browsers. Spritesmith isn't going anywhere soon.

**Comment by Romanx** [comment]
@twolfson you're welcome. Thanks for adding to the docs 👍
