### ISSUE TITLE
Quality option not working with gmsmith

### ISSUE THREAD

**Issue by jmahony** [twolfson/gulp.spritesmith#28]
I'm trying to swap the engine used to generate sprites from pixelsmith to gmsmith. Pixelsmith left artifacts in the image. The quality option has no effect on the sprite image.

I'm passing in the following options:

```
options: {
    imgName: 'HP_Sprite_NonTransparent.jpg',
    cssName: 'HP_Sprite_NonTransparent.css',
    engine: require('gmsmith'),
    engineOpts: {
        imagemagick: true
    },
    exportOpts: {
        quality: 50
    }
}
```
package.json
```
"devDependencies": {
    "gm": "^1.17.0",
    "gmsmith": "^0.4.5",
    "gulp": "gulpjs/gulp.git#4.0"
    "gulp-imagemin": "^2.1.0",
    "gulp.spritesmith": "^2.4.0"
},
```
I have ImageMagick installed as well!

Any help would be appreciated!

**Comment by twolfson** [comment]
Can you copy/paste the entire `gulp.task` definition? How are you verifying that quality is not being used?

**Comment by jmahony** [comment]
Here's my task.
```
gulp.task('sprite', function (cb) {
    return gulp.src("images/sprites/*.*")
    .pipe(spriteSmith({
        imgName: 'HP_Sprite_NonTransparent.jpg',
        cssName: 'HP_Sprite_NonTransparent.css',
        engine: require('gmsmith'),
        engineOpts: {
            imagemagick: true
        },
        exportOpts: {
            quality: 50
        }
    })).pipe(gulp.dest(paths.cssDir));
});
```

I'm verifying it by setting the quality to extremes and checking if there's a difference, also the file size doesn't change. I've tried manually deleting the images between each attempt.

Cheers.

**Comment by twolfson** [comment]
Cool, everything looks good there. I will try to reproduce the issue by the end of the weekend.

**Comment by twolfson** [comment]
Looked into this in https://gist.github.com/twolfson/34be56423842626e64bd

It looks like my documentation is inconsistent. Under `imgOpts`, I am providing an example for `exportOpts`. `exportOpts` is a valid option for `spritesmith` but I chose to rename it for `gulp.spritesmith` and `grunt-spritesmith`. To fix your issue, use the following config:

```js
gulp.task('sprite', function (cb) {
    return gulp.src("images/sprites/*.*")
    .pipe(spriteSmith({
        imgName: 'HP_Sprite_NonTransparent.jpg',
        cssName: 'HP_Sprite_NonTransparent.css',
        engine: require('gmsmith'),
        engineOpts: {
            imagemagick: true
        },
        imgOpts: {
            quality: 50
        }
    })).pipe(gulp.dest(paths.cssDir));
});
```

I will be correcting the `gulp.spritesmith` and `grunt-spritesmith` documentation shortly.

**Comment by jmahony** [comment]
Thank you, that fixed it!
