### ISSUE TITLE
Only generate sprite if changed

### ISSUE THREAD

**Issue by denisz1** [twolfson/gulp.spritesmith#29]
In other gulp modules, I can use the `gulp-changed` plugin, to detect if soemthing changes before regenerating.

It doesn't work here though:

    gulp.task('sprite', function () {
      gulp
        .src(pathsin)
        .pipe(changed())                          // <-- doesnt work
        .pipe(spritesmith({
          imgName: 'sprite.png',
          cssName: 'sprite.less'
        }))
        .pipe(gulp.dest(pathout));
    });

I expect it is because this plugin does something to the stream, or because it cannot detect changes in multiple input files. Don't know exactly.

So: how do I avoid spriting if there are no changes?

**Comment by twolfson** [comment]
It looks like you are missing the destination file for `changed`. It requires putting the same destination folder:

https://www.npmjs.com/package/gulp-changed

```js
gulp.task('sprite', function () {
  gulp
    .src(pathsin)
    .pipe(changed(pathout))
    .pipe(spritesmith({
      imgName: 'sprite.png',
      cssName: 'sprite.less'
    }))
    .pipe(gulp.dest(pathout));
});
```

**Comment by denisz1** [comment]
No that wasn't it. I don't think `gulp-changed` is a good fit. But, `gulp-newer` is, as it can do a 1:many match for changed files. There is [an example here](https://github.com/twolfson/gulp.spritesmith/issues/17).

**Comment by twolfson** [comment]
Ah, right. `gulp-changed` seems to filter out images from the pipe. We would like something that instead reruns the task. `gulp-newer` supports re-running the task entirely as in the linked issue.
