### ISSUE TITLE
spritesheet-templates@8.3.0 update converts dashes to underscores by default

### ISSUE THREAD

**Issue by sinan** [twolfson/gulp.spritesmith#30]
With https://github.com/twolfson/gulp.spritesmith/commit/b4fb6bd085f6978b232588798b72ac39dfa77a77 our build script started putting wrong variable names on stylus outputs for sprites. (temporarily fixed it by using an earlier version)

I have a basic transform for variable names as below:

```coffeescript
gulp = require 'gulp'
spritesmith = require 'gulp.spritesmith'

nameHelper = (folder, pixelRatio, sprite) ->
  sprite.name = "#{pixelRatio}x_#{folder}_#{sprite.name}";
  return sprite

module.exports = (folder, pixelRatio) ->

  stream = gulp.src "./#{folder}/lib/sprites/#{pixelRatio}x/**/*.png"
    .pipe spritesmith
      imgName   : "#{folder}@#{pixelRatio}x.png"
      cssName   : "sprite@#{pixelRatio}x.styl"
      imgPath   : "/a/p/p/#{folder}@#{pixelRatio}x.png"
      algorithm : 'binary-tree'
      padding   : 5
      cssFormat : 'stylus'
      cssVarMap : nameHelper.bind stream, folder, pixelRatio

  return stream
```
when my `folder` is _main-app_ and the `sprite.name` is _nice-icon-16_ the output styl file this provides becomes like this:

```stylus
$1x_main_app_nice_icon_16_name = '1x_main_app_nice_icon_16;
$1x_main_app_nice_icon_16_x = 60px;
$1x_main_app_nice_icon_16_y = 0px;
...
```
where _main-app_ becomes _main_app_ and _nice-icon-16_ becomes _nice_icon_16_ .

It looks like now dashes are converted to underscores by default, and digging more took me here https://github.com/twolfson/spritesheet-templates/issues/37 but unfortunately couldn't see the commit causing this, so reporting here.

**Comment by twolfson** [comment]
Ah, sorry about that. I didn't mean for it to be a breaking change but that is an upcoming one to make casing consistent and fully mutable. I will revert `gulp.spritesmith` and `grunt-spritesmith` in a minor patch and re-introduce it via a major release.

I will perform the revert some time before the end of the weekend. In the interim, using `gulp.spritesmith@2.5.0` should maintain the previous behavior.

**Comment by sinan** [comment]
:+1:

**Comment by twolfson** [comment]
I have reverted the changes and released `gulp.spritesmith@3.7.0`.

**Comment by twolfson** [comment]
The changes have been re-introduced as a major release in `grunt-spritesmith@4.0.0` and `gulp.spritesmith@3.0.0`. I hope the upgrade doesn't cause too much trouble =/

**Comment by sinan** [comment]
thanks for the notice :+1: I'll let you know once I test.
