### ISSUE TITLE
update to gulp-sass 1.3.3 (latest) breaks sprite positioning

### ISSUE THREAD

**Issue by bkellgren** [twolfson/gulp.spritesmith#31]
I apologize, I don't have time to set up an example project in a vacuum right now but wanted to make you aware it seems both gulp.spritesmith version 2.8.0 and 3.0.0 are not positioning correctly with the latest gulp-sass (version 1.3.3)

**Comment by twolfson** [comment]
What versions were you using previously that worked so we have a point of reference?

**Comment by bkellgren** [comment]
2.5.1 was the previous version that we used of your package but I assume that will break with gulp-sass 1.3.3 as well, haven't tested that yet 

Of course it could be an issue in gulp sass but since the only symptoms we saw was spriting with spritesmith I figured I'd reach out to you 

Again sorry I don't have time to mock it all out right now but hope that helps

**Comment by twolfson** [comment]
Yea, no worries. I will try to take a look this weekend but it will be by the end of the next one (Mar 1) at the latest.

**Comment by bkellgren** [comment]
Much appreciated Todd, will look forward to the next update.

Just to recap for anyone else who stumbles upon this thread,  all of the recent versions of gulp.spritesmith work just fine with gulp-sass 1.3.2 but not 1.3.3.

**Comment by twolfson** [comment]
I have created a gist to reproduce the issue. However, I cannot find one that is specific between the different versions of `gulp-sass`.

https://gist.github.com/twolfson/2ffb37b78070c1721738

However, I did find that the `sprites` mixin does not behave properly with `node-sass` and consequently `libsass`. It looks like nested references to variables (e.g. nested arrays) isn't currently supported. I am going to look into finding or opening a corresponding issue and making a comment in the templates.

Outside of that, can you provide more info on the issue you were running into? What does your SASS/SCSS look like? What OS are you on? What version of `node`/`io` are you on?

**Comment by twolfson** [comment]
Ah, it looks like I falsely claimed something. `libsass` only seems to be misbehaving when I use a single sprite since that is being as a reference and not a `list` of variables. I am going to look into reproducing with multiple sprites.

**Comment by twolfson** [comment]
I don't see any issues with compiling using `gulp-sass@1.3.3`. Can you please answer the questions I asked 2 comments ago?

> Can you provide more info on the issue you were running into? What does your SASS/SCSS look like? What OS are you on? What version of node/io are you on?

I am going to look into adding a patch to better handle the single sprite case but I doubt that is what you are encountering.

**Comment by twolfson** [comment]
For reference, I have added the fixes/warnings for single sprite cases to `spritesheet-template@9.1.0`, `grunt-spritesmith@4.1.0`, and `gulp.spritesmith@3.1.0`.

**Comment by twolfson** [comment]
@bkellgren has gone silent on this issue with no new reports of it occurring since the fixes mentioned in the previous comment. Going to consider this resolved for now.
