### ISSUE TITLE
Can spritesmith generate responsive sprites?

### ISSUE THREAD

**Issue by denisz1** [twolfson/gulp.spritesmith#32]
Responsive sprites means they scale with the browser, and also, that you can make an image fit its container, etc.

Does spritesmith already generate this sort of data? Has anyone done this, any tips?

The typical calculation is:

    width:  @image-width;
    height: @image-height;
  
    background-size: ((@sprite-total-width  / @image-width)  * 100%)
                     ((@sprite-total-height / @image-height) * 100%);
                   
    // x or y may be 0% depending on stacking of the sprite (vertical vs horizontal)                   
    background-position: ((@image-offset-x / (@sprite-total-width  - @image-width))  * 100%)
                         ((@image-offset-y / (@sprite-total-height - @image-height)) * 100%);
                       
There is [some background here](http://www.browniesblog.com/A55CBC/blog.nsf/dx/responsive-css-sprites.html?opendocument&comments) and [here](https://stackoverflow.com/a/23419418/3959480).

It's fiddly, and I need to do it all by hand. Has anyone managed to do something like this with less and spritesmith?

**Comment by twolfson** [comment]
There was a discussion in `grunt-spritesmith` about this. I decided to not include it as a main part of the library due to compatibility and maintenance concerns. There should be some useful examples in there though:

https://github.com/Ensighten/grunt-spritesmith/issues/84

**Comment by denisz1** [comment]
Hey @twolfson thanks for that link, I understand your concern regarding maintenance.

That said, it's 2015 and everything is responsive. If you can't get them responsive then you can't use a sprite and so you need to go back to using individual images! Yuck!

There are a number of approaches, I tried them all, [and I settled on one that](https://gist.github.com/Malkyne/9492320):
- doesn't use background-size (which is CSS3)
- works for images of any size (most approaches require your sprite's images to be the same size)
- works for images at any offset (most approaches require your sprite to be a horizontal/vertical strip)
- is very easy to implement
- so far works on all browsers I've tested

The only additions I made to the generated spritesheet:

    .sprite-responsive(@sprite) {

      @sprite_width:  extract(@sprite, 7);
      @sprite_height: extract(@sprite, 8);
      @image_width:   extract(@sprite, 5);
      @image_height:  extract(@sprite, 6);
      @x:             extract(@sprite, 1);
      @y:             extract(@sprite, 2);
      @y_offset:      extract(@sprite, 4);

      width:          100% *  @sprite_width                        / @image_width;
      margin-top:     100% *  @y_offset                            / @image_width;
      margin-bottom: -100% * (@sprite_height - @y - @image_height) / @image_width;
      margin-left:    100% *  @x                                   / @image_width;

      // explanation:
      // width         = 100% * sprite width                            / image width
      // margin-top    = 100% * distance from top of sprite to image    / image width
      // margin-bottom = 100% * distance from bottom of sprite to image / image width
      // margin-left   = 100% * distance from left of sprite to image   / image width
  
    }

    .sprite  {
      height: auto;
      overflow: hidden;
    }
    .sprite >img {
      display: block;
    }

To use it you need this markup:

    <div class="sprite">                      // <-- you need a wrapper, no biggie
      <img src="/foo/bar/mysprite.png" class="mysprite-foo" />
    </div>

And this less:
    
    img.mysprite-foo { .sprite-responsive(@mysprite-foo); }
    img.mysprite-bar { .sprite-responsive(@mysprite-bar); }
    img.mysprite-baz { .sprite-responsive(@mysprite-baz); }

As you can see, it's very easy, bulletproof, and there's not much to maintain.

If you don't decide to add this functionality, I at least hope your other users can benefit from this. Responsive sprites are a pain to get working, maybe a link to this thread would help.

**Comment by twolfson** [comment]
I understand the viewpoint and still am going to decline. For maintenance, it does not mean maintaining 1 template but multiple templates in `spritesheet-templates` (currently 6 of them would be suitable) since they are each different languages.

That being said, `spritesmith` is accessible to using external templates. If you want, you can create a node module that serves these templates as strings for usage:

```js
var responsiveSpritesheetTemplates = require('responsive-spritesheet-templates');
// At import time, runs `fs.readFileSync` on its templates

spritesmith({
  // cssName, imgName,
  cssTemplate: responsiveSpritesheetTemplates.less
})
```

On a side note, I would label this approach as fluid sprites. Responsive means that the image changes as the page changes size. However, there are other approaches beyond changing pixel for pixel. For example, with icons we change shapes to be better visible at smaller sizes:

http://blog.useiconic.com/designing-iconic-across-different-sizes/

**Comment by denisz1** [comment]
@twolfson Cool that template idea is great.

Fluid sprites: yes you're right. If you want responsive, you can play with the css on that wrapper and img, and it scales nicely.

**Comment by denisz1** [comment]
@twolfson  Sorry one last thing, having trouble with that template idea. 

Is it supposed to "add" my new stuff to your base template, or presumably, replace it altogether? If the latter, do I just copy-paste your base tempalte into my one?

**Comment by twolfson** [comment]
You can do either case. For adding on, you can do something fancy like read in the template (`fs.readFileSync(require.resolve('spritesheet-templates/lib/templates/less.template.mustache'))`) and append your new mixin, effectively overriding the `sprite` mixin. However, that would be confusing to people who load the template and see 2 sets of comments and mixins.

It would be best to copy/paste and adjust to your needs (e.g. comment/mixin). You don't necessarily need to preserve things like most variables but it might be nice to keep in case of emergency.

**Comment by denisz1** [comment]
@twolfson Thanks again. Awesome library.

**Comment by krautnerds** [comment]
I'm also looking for a possibility to create responsive/fluid sprites. @denisz1 Is it possible for you to host your template on github or as a gist somewhere? That would be great :)

Thanks!

**Comment by stevenw00** [comment]
Works great. I have created an example gist which shows the custom template I used to create a SCSS file.

https://gist.github.com/stevenw00/601182f8b90f48182709

**Comment by kevinmpowell** [comment]
@stevenw00 thanks for that scss solution. I made a couple tweaks:
https://gist.github.com/kevinmpowell/97357409b9af7625b257

I had an existing CSS role `max-width: 100%;` on all my images which was breaking this functionality so I explicitly set that to `max-width: none;`

The margin-bottom calculation was incorrect. I think it would work if your sprite was one horizontal strip, but mine wasn't so I was seeing issues. My fork made the change.

**Comment by jasonlav** [comment]
It is 2016, background-size CSS3 property is well supported and responsive websites are the norm. If you must support the 0.3% of users who are still using IE8, then don't use this version.

Thanks to @stevenw00 and @denisz1 for leading the way on this.

https://gist.github.com/jasonlav/32e72a4afc348cd176dcd52cf9a45dbe
