### ISSUE TITLE
Broken relative paths?

### ISSUE THREAD

**Issue by cahamilton** [twolfson/gulp.spritesmith#36]
First of all, thanks for the great plugin - it's a real lifesaver. Apologies ahead of time as well, JavaScript isn't exactly my forte. 

I'm currently experimenting with transitioning between grunt-spritesmith -> gulp-spritesmith and think I've noticed an issue with how relative paths are calculated in output CSS. 

grunt-spritesmith looks like its calculating a relative spritePath via dest & destCSS (a full filepath), whereas Gulp is doing it via imgName & cssName (filenames with no filepath). So between the transition, I've ended up with something along the lines of:
```
.grunt {
  background-image: url('../../../../../site/m/images/sprite.png');
}

.gulp {
  background-image: url('sprite.png');
}
```
I've managed to work around the issue by passing in a filepath to imgName & cssName and amending gulp.dest, but was curious as this doesn't seem like intended functionality.

**Comment by twolfson** [comment]
As a note, this is `gulp.spritesmith`, not `gulp-spritesmith` but I believe the discrepency exists in both.

I don't think I fully considered this when writing the plugin. The relative filepath is determined between `imgName` and `cssName`. Techically, we could use the same convention as in `grunt`. However, that isn't really `gulp's` style as you mentioned.

The alternative to this is `imgPath` which allows for specifying the path to use in CSS to resolve the `img`:


```js
{
  cssName, imgName,
  imgPath: '../../../../../site/m/images/sprite.png'
}
```

**Comment by cahamilton** [comment]
Yes apologies, I did mean to say `gulp.spritesmith` there.

With a little tweaking, I've managed to get a better working solution for what I'm looking for. Thanks for your help again.
