### ISSUE TITLE
No Retina sprite when individual streams for images and CSS is used

### ISSUE THREAD

**Issue by MaciejJanyska** [twolfson/gulp.spritesmith#38]
Retina sprite is not generated when i use  individual streams:

```
spriteData.img
    .pipe(gulp.dest('path/to/image/folder/'));

spriteData.css
    .pipe(gulp.dest('path/to/css/folder/'));
```

What am I doing wrong? Everyting is fine when `spriteData.pipe(gulp.dest('path/to/output/'));` is used.

**Comment by twolfson** [comment]
This was fixed in `3.5.3`. Please make sure you are on the latest version.

```bash
npm install gulp.spritesmith@latest
```
