### ISSUE TITLE
Ignoring retina size

### ISSUE THREAD

**Issue by radist2s** [twolfson/gulp.spritesmith#41]
Hi, I was away and i missed this [comment](https://github.com/twolfson/gulp.spritesmith/pull/37#issuecomment-87946011).

Sometimes my retina sprites aren't 2x, because Adobe Extract does something wrong when it exports 2x sprites(sprites can be less for 1 pixel if it is a vector image).

Actually I committed this for myself and i was not going to push it into your repository.
I do not insist that this commit should be pushed into main tree, but for me it was helpful.

**Comment by twolfson** [comment]
Ah, that makes sense. There was another PR that came in with a similar option:

https://github.com/twolfson/gulp.spritesmith/pull/39

However, we resolved the issue (and any possible spritesheet scaling issues) by insisting usage of an image normalizer to make the retina images properly 2x via padding:

https://github.com/twolfson/gulp.spritesmith/pull/39#issuecomment-89427454
