### ISSUE TITLE
Why  gulp.spritesmith and not gulp-spritemith ?

### ISSUE THREAD

**Issue by bactisme** [twolfson/gulp.spritesmith#42]
Like all the other gulp package ?

My OCD doctor said that it doesn't mater, but it does !

**Comment by twolfson** [comment]
This library was originally `gulp-spritesmith` but at the time of release, another `gulp-spritesmith` was published a few hours before. As a result, we renamed to `gulp.spritesmith`.

We opened an issue to discuss this but didn't come to an agreement.

https://github.com/Otouto/gulp-spritesmith/issues/3
