### ISSUE TITLE
Multiple globbing issue 

### ISSUE THREAD

**Issue by Vargentum** [twolfson/gulp.spritesmith#44]
When I use multiple globbing, like `sprites/{,**/}*.png`, gulp.spritesmith duplicates all source images inside output sprite. I solved this problem by using an array:
```
src: [
  'sprites/**/*.png'
  'sprites/*.png'
]
```

Is it possible to support multiple globbing?

**Comment by twolfson** [comment]
I believe you are confused with how `glob` functions. `**/*.png` will include all `*.png` in `/` as well as `*.png` in any directory and nested directories (e.g. `folder1/*.png`, `folder1/folder2/*.png`). This deduplication issue can be solved by using only `sprites/**/*.png` as your glob.

```js
src: 'sprites/**/*.png'
```
