### ISSUE TITLE
gulp-csso throwing Error: Please check the validity of the CSS block starting from the line #140 

### ISSUE THREAD

**Issue by bdelaney** [twolfson/gulp.spritesmith#46]
I set up two spritesmith tasks in Gulp v 3.8.5 that both use gulp.src('images/**/*.png').

The first task pipes the src to spritesmith ONLY, works fine. I get the expected png/css files.

The second task uses your example of streaming 'continuing the pipeline' and I copied the code exactly, changing only the gulp.dest . Running that produces an error.
`Error: Please check the validity of the CSS block starting from the line #140 `
That second task was working fine using the separate streams when my gulp.src was a single directory. It only began to error when I changed my gulp.src to the glob expression.

The errors all appear to be in gulp-csso.

Here is the gulpfile code for the second task. I commented out imgPath to be sure that was not causing the issue.

```gulpfile
 gulp.task('sprite', function () {
  // Generate our spritesheet
  var spriteData = gulp.src(['images/**/*.png', '!images/favicons/**']).pipe(spritesmith({
    imgName: 'sprite-gallery.png',
    cssName: 'sprite-gallery.css'
    /*imgPath: '../sprites/sprite-gallery.png'*/
  }));

  // Pipe image stream through image optimizer and onto disk
  spriteData.img
      .pipe(imagemin())
      .pipe(gulp.dest('dist/sprites'));

  // Pipe CSS stream through CSS optimizer and onto disk
  spriteData.css
      .pipe(csso())
      .pipe(gulp.dest('dist/css'));
});
```

**Comment by twolfson** [comment]
Hm, strange. Everything looks like it should work. Can you paste the `css` output and the `require's` of this code sample too?

**Comment by bdelaney** [comment]
Never got any CSS output. Or image file. That same gulp.src works fine in the single function task. Do you want me to paste that output in here?

**Comment by twolfson** [comment]
Yep, that's the output I am talking about. If it's under 40 lines, then yes paste it in. Otherwise, maybe paste it in a gist and link it?

https://gist.github.com/

**Comment by bdelaney** [comment]
180 lines. Here is the Gist
https://gist.github.com/bdelaney/418f9f533dc41202aaff.js"

**Comment by twolfson** [comment]
I have found the issue. It is this selector:

```css
.icon-overview_left_1@2x {
  background-image: url(sprite.png);
  background-position: 0px -2232px;
  width: 800px;
  height: 800px;
}
```

We are not allowed to have an `@` in our CSS selectors which is causing CSSO to choke. Here are some solutions:

- Update your file name to not have an `@` in it (e.g. `overview_left_1_2x.png`)
- Use `cssVarMap` to dynamically rename the file (e.g. `cssVarMap: function (sprite) { sprite.name = sprite.name.replace(/@/g, '_');`)
    - https://github.com/twolfson/gulp.spritesmith/tree/3.6.1#variable-mapping
- It seems like this is a sprite intended for a retina task so either upgrade everything in the task to support retina or filter it out

I will need to think a little before deciding if we should automatically coerce invalid CSS selector character or not.

**Comment by bdelaney** [comment]
Oh, duh. I am sorry for not thinking of that myself. Easy enough to work around for now.
thanks for your attention to this. I'll be 'gratipaying' you again for this great suite of tools. And your support, par excellence.

**Comment by twolfson** [comment]
No worries. I am glad it worked out easily. Thanks for your support! =)

**Comment by bdelaney** [comment]
Well, Spritesmith has been incredible useful to me in the last several months, and you even got me to cross over to Gulp for the streaming functionality. So, Thank You!
