### ISSUE TITLE
Error: Unsupported interlace method.

### ISSUE THREAD

**Issue by Jsonzhang** [twolfson/gulp.spritesmith#50]
gulp.task('sprite', function () {
            var spriteData = gulp.src(paths.html +'/images/sprites/*.png').pipe(spritesmith({
                imgName: 'ccc.png',
                cssName: 'ccc.css'
            }));
            return spriteData.pipe(gulp.dest(paths.html + '/images/'));
        });

result in 

        events.js:85
              throw er; // Unhandled 'error' event
                    ^
        Error: Unsupported interlace method.
            at Stream.<anonymous> (/Users/Json/project/gongyi_proj/trunk/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/pngparse/index.js:205:28)
            at Stream.emit (events.js:107:17)
            at Object.exports.parseBuffer (/Users/Json/project/gongyi_proj/trunk/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/pngparse/index.js:529:5)
            at handlePNG (/Users/Json/project/gongyi_proj/trunk/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:16:12)
            at doParse (/Users/Json/project/gongyi_proj/trunk/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:103:7)
            at /Users/Json/project/gongyi_proj/trunk/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:175:7
            at fs.js:334:14
            at /Users/Json/project/gongyi_proj/trunk/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
            at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by twolfson** [comment]
This has been a long standing issue in `grunt-spritesmith` (https://github.com/Ensighten/grunt-spritesmith/issues/80).

The underlying cause is `pixelsmith` (default `spritesmith`) engine uses `pngparse` which doesn't currently support interlaced images (https://github.com/darkskyapp/pngparse/issues/10).

The suggested workarounds until `pngparse` adds this support is to:

- Use a different engine (e.g. `phantomjssmith`)
- Preprocess images into a progressive format
    - This can be done at export time from Photoshop or whatever image editing tool is being used to generate the original sprites
    - This can be done via another `gulp` task which runs something like `gm`
        - https://www.npmjs.com/package/gulp-gm/

**Comment by Jsonzhang** [comment]
okey , i have used `phantomjssmith` to avoid this error successfully. ths.

**Comment by Jsonzhang** [comment]
it work.

**Comment by twolfson** [comment]
While the workarounds work, I would prefer to keep this issue open since it is still an unsolved problem =/

**Comment by lukeapage** [comment]
@twolfson I've been working on fixing pngjs (I preferred the structure to pngparse) and I've added 1/2/4/16 bit support and interlace.
https://github.com/lukeapage/pngjs2

**Comment by twolfson** [comment]
Cool, I swapped `pngparse` with `pngjs2` inside of my local copy of `get-pixels` and it seems to work with some test images. Are we aware of any compatibility issues that `pngparse` exists yet `pngjs2` doesn't yet support?

```js
// Old code in`get-pixels`
var pngparse = require('pngparse')
pngparse.parse(data, function(err, img_data) {

// New code in `get-pixels`
var pngjs2 = require('pngjs2')
var png = new pngjs2.PNG();
png.parse(data, function(err, img_data) {
```

**Comment by lukeapage** [comment]
cool. Give me some days - there are a couple of subtle issues in the png
suite test results I've found and I'm going to tidy up some more then
release v1. I will see if there are any tests in pngparse i can port too.

**Comment by twolfson** [comment]
Sounds great. Thanks for working on this =)

**Comment by artem-malko** [comment]
@lukeapage @twolfson So, how the things?)

**Comment by lukeapage** [comment]
the issues i mentioned were down to gamma correction and that every browser does it differently.  pngparse ignores the gamma block, so the default behaviour won't differ (gamma correction is an optional extra in pngjs2). 
I have added issues for all the things i want to do before changing the version to 1 to indicate a good stable release, its mainly code quality and a few minor features. I guess that might take a week or so. 
that being said,  im pretty happy,  it now passes all the pngsuite images, if youd like to start using it.

**Comment by twolfson** [comment]
It's been 1 year and 2 months since Ensighten/grunt-spritesmith#80 was opened. I think waiting another week for stability won't kill us.

@lukeapage Please don't feel rushed to complete it faster; I would prefer a working maintainable PNG library to a working difficult to maintain one =)

**Comment by lukeapage** [comment]
yeah fine,  the bones are there, I'm just enjoying that its a small enough project to go perfectionist on it.

**Comment by lukeapage** [comment]
I've released v1.

> Are we aware of any compatibility issues that pngparse exists yet pngjs2 doesn't yet support?

No, It tests every image from the png test suite and I've ported all of png-parses test suite.

There is one difference between pngparse v2 and pngjs2 - the parsed image is *always* 4 channels RGBA in pngjs2. However looking at https://github.com/scijs/get-pixels/blob/master/node-pixels.js#L15 and the package.json I can see node-pixels is using pngparse v1, which returns the same output as pngjs2 - so a straight swap will work fine.

Will you make a PR against get-pixels then? Let me know if you encounter any issues.

**Comment by lukeapage** [comment]
get-pixels is for browser and node, so before its upgraded pngjs2 needs to work with browserify

**Comment by lukeapage** [comment]
> get-pixels is for browser and node, so before its upgraded pngjs2 needs to work with browserify

pngparse uses zlib and stream too, so browserify must provide browser polyfills (e.g. https://github.com/devongovett/browserify-zlib). pngjs2 doesn't use any dependencies above pngparse

**Comment by twolfson** [comment]
Afk atm but get-pixels uses its dom-pixels.js file for the browser. This
doesn't need a PNG parser as it uses canvas elements instead.

**Comment by lukeapage** [comment]
ah.. thanks. I raised a PR anyway.. https://github.com/scijs/get-pixels/pull/24

**Comment by artem-malko** [comment]
@lukeapage @twolfson Do you have any news?)

**Comment by twolfson** [comment]
Nope, still waiting for the `get-pixels` PR to be landed. I think we can bump the issue after 14 days though (it's been 5 days). Mikola is pretty responsive/helpful.

http://issuestats.com/github/scijs/get-pixels/

**Comment by artem-malko** [comment]
@twolfson @lukeapage Ok, will be waiting

**Comment by pdokas** [comment]
I asked for info on what it’ll take to merge https://github.com/scijs/get-pixels/pull/24 since I too am gated from using spritesmith until pixelsmith supports interlaced pngs.

**Comment by artem-malko** [comment]
@lukeapage @twolfson Is there any news?)

**Comment by lukeapage** [comment]
@artem-malko there is no news until the PR linked above gets some response

**Comment by twolfson** [comment]
Sorry for the delay on this. The dependent PR was landed a few days ago but I got back from vacation today. I will attempt to make a release shortly.

**Comment by twolfson** [comment]
Everything seems to work nicely. We moved to `pngjs2` in `gulp.spritesmith@4.1.0`. Thanks again @lukeapage for all your work =)
