### ISSUE TITLE
Drop "icon-" from the generated sprite css using gulp.spritesmith

### ISSUE THREAD

**Issue by dilipkumar2k6** [twolfson/gulp.spritesmith#51]
I am using gulp.spritesmith to automate sprite image and css generation. All works good except the generated css is haivng "icon-" prefix. I don't want to add this prefix as I have existing HTML markup and I don't want to change the markup. 
Following is my gulp task.
        'use strict';
        var gulp = require('gulp');
        var spritesmith = require('gulp.spritesmith');

        gulp.task('sprite', function () {    

            var spriteData =
                    gulp.src('./sprite/*.*') // source path of the sprite images
                    .pipe(spritesmith({
                        imgName: 'sprite.png',
                        cssName: 'sprite.css'
                    }));

            spriteData.img.pipe(gulp.dest("./css")); // output path for the sprite
            spriteData.css.pipe(gulp.dest("./css")); // output path for the CSS
        });
Following is my generated css.
 
        .icon-icon1 {
          background-image: url(sprite.png);
          background-position: 0px 0px;
          width: 120px;
          height: 120px;
        }
        .icon-icon2 {
          background-image: url(sprite.png);
          background-position: -120px 0px;
          width: 120px;
          height: 120px;
        }
Please help to supress "icon-".

**Comment by twolfson** [comment]
This is supported via `cssOpts.cssSelector`. We can adjust the selector for your use case with:

```js
cssOpts: {
  cssSelector: function (sprite) {
    // Use sprite name as its own selector (e.g. `icon1` -> `.icon1`)
    return '.' + sprite.name;
  }
}
```

https://github.com/twolfson/spritesheet-templates/tree/9.6.1#css

**Comment by dilipkumar2k6** [comment]
Thanks. it worked.
