### ISSUE TITLE
cssFormat option breaks output with retina variables.

### ISSUE THREAD

**Issue by YozhEzhi** [twolfson/gulp.spritesmith#54]
When I have ```cssFormat : "scss"```
in my gulpfile.js, than I have no ```@mixin retina-sprite``` and 2x-variables.

For example I have ```$icon-name: 'icon';``` but there is no ```$icon-2x-name: 'icon-2x';```

**Comment by twolfson** [comment]
As documented in the README, our retina configuration uses a different set of spritesheet templates. To remedy the issue, we will need to use `cssFormat: "scss_retina"`

https://github.com/twolfson/gulp.spritesmith/tree/3.8.2#retina-parameters

https://github.com/twolfson/spritesheet-templates#retina-templates
