### ISSUE TITLE
End event on image streams fired prematurely

### ISSUE THREAD

**Issue by jedmao** [twolfson/gulp.spritesmith#55]
I'm merging both the image and css streams with [event-stream#merge](https://www.npmjs.com/package/event-stream), but my task is still ending prematurely. This is similar to  https://github.com/twolfson/gulp.spritesmith/issues/48. Here's my setup:

```js
gulp.task('styles', done => {
  let sheetCount = 0;
  gulp.src('styles/sheets/*')
    .pipe(tap(sheetFolder => {
      gutil.log('++sheetCount:', ++sheetCount);
      buildSprites(sheetFolder).on('end', end);
    }));
  function end() {
    gutil.log('--sheetCount:', --sheetCount);
    if (sheetCount === 0) {
      done();
    }
  }
});

function buildSprites(sheetFolder) {
  const sheetName = sheetFolder.relative;
  const spriteData = gulp.src(join(sheetFolder.path, 'images', '*.png'))
    .pipe(plumber())
    .pipe(spritesmith({
      imgName: sheetName + '.png',
      cssName: sheetName + '.json',
      padding: 10
    }));
  const spritesDestPath = 'build/public/images/sprites';
  return eventStream.merge(
    spriteData.img
      .pipe(plumber())
      .pipe(imagemin())
      .pipe(logFile())
      .pipe(gulp.dest(spritesDestPath)),
    spriteData.css
      .pipe(logFile())
      .pipe(gulp.dest(spritesDestPath))
  );
}

function logFile() {
  return tap(file => {
    gutil.log(relative(file.base, file.path));
  });
}
```

And here's what I get in the CLI:

```
13:00 $gulp styles
[13:01:12] Requiring external module babel-core/register
[13:01:14] Using gulpfile Z:\project\gulpfile.babel.js
[13:01:14] Starting 'styles'...
[13:01:14] ++sheetCount: 1
[13:01:14] ++sheetCount: 2
[13:01:14] ++sheetCount: 3
[13:01:15] page2.json
[13:01:15] --sheetCount: 2
[13:01:15] page1.json
[13:01:15] global.json
[13:01:15] --sheetCount: 1
[13:01:15] --sheetCount: 0
[13:01:15] Finished 'styles' after 569 ms
[13:01:15] page2.png
[13:01:15] Plumber found unhandled error:
 Error: write after end
[13:01:15] gulp-imagemin: Minified 1 image (saved 1.57 kB - 28.3%)
[13:01:15] page1.png
[13:01:15] Plumber found unhandled error:
 Error: write after end
[13:01:15] gulp-imagemin: Minified 1 image (saved 4.93 kB - 44.6%)
[13:01:15] global.png
[13:01:15] Plumber found unhandled error:
 Error: write after end
[13:01:15] gulp-imagemin: Minified 1 image (saved 4.57 kB - 18.7%)
```

As you can see, the end event is firing after the JSON files are written, but before the image files have finished writing.

Any ideas?

**Comment by jedmao** [comment]
UPDATE: If I return only the image stream without merging, the end event is fired fine.

**Comment by jedmao** [comment]
UPDATE: Switching from [event-stream](https://www.npmjs.com/package/event-stream) to [merge-stream](https://www.npmjs.com/package/merge-stream) doesn't seem to make a difference.

**Comment by jedmao** [comment]
Interesting. Removing the pipes to `logFile()` seemed to fix everything. Not sure what's happening w/ gulp-tap, but at least I fixed the issue. Doesn't seem to be related to gulp.spritesmith though, so I'm closing.

**Comment by twolfson** [comment]
Cool, glad to hear it all worked out =)

**Comment by jedmao** [comment]
@twolfson I'm sorry to say I'm still experiencing this issue. If I'm not mistaken, I think the end event for the css stream is ending not only the css stream, but also the image stream.

**Comment by jedmao** [comment]
@twolfson I just realized there are no tests for the merge scenario, which is stated on the readme. I am unable to write a failing test, however, as reported in https://github.com/twolfson/gulp.spritesmith/issues/56.

**Comment by twolfson** [comment]
We test the `merge` scenario in the `two-streams` tests which can be found here:

https://github.com/twolfson/gulp.spritesmith/blob/3.8.2/test/gulp-spritesmith_test.js#L54-L68

https://github.com/twolfson/gulp.spritesmith/blob/3.8.2/test/gulpfile.js#L49-L59

**Comment by twolfson** [comment]
I would place my money on `gulp-tap` being the issue. It has no tests and uses `emit` over `write` for streams (which can cause compatibility issues).

https://github.com/geejs/gulp-tap/blob/v0.1.3/src/tap.coffee#L50-L57

I suggest using `through` instead:

https://github.com/dominictarr/through

```js
gulp.task('styles', => {
  let sheetCount = 0;
  return gulp.src('styles/sheets/*')
    .pipe(through(sheetFolder => {
      gutil.log('++sheetCount:', ++sheetCount);
      this.push(sheetFolder);
    }))
    .pipe(sheetFolder => {
      gutil.log('--sheetCount:', --sheetCount);
    });
});

function buildSprites(sheetFolder) {
  const sheetName = sheetFolder.relative;
  const spriteData = gulp.src(join(sheetFolder.path, 'images', '*.png'))
    .pipe(plumber())
    .pipe(spritesmith({
      imgName: sheetName + '.png',
      cssName: sheetName + '.json',
      padding: 10
    }));
  const spritesDestPath = 'build/public/images/sprites';
  return eventStream.merge(
    spriteData.img
      .pipe(plumber())
      .pipe(imagemin())
      .pipe(logFile())
      .pipe(gulp.dest(spritesDestPath)),
    spriteData.css
      .pipe(logFile())
      .pipe(gulp.dest(spritesDestPath))
  );
}

function logFile() {
  return through(file => {
    gutil.log(relative(file.base, file.path));
    this.push(file);
  });
}
```

**Comment by jedmao** [comment]
Excellent! That works! I just opened up an issue with gulp-tap. I'll be using through from now on. I just thought tap was a clever name and it made sense to me. Whatever works!

**Comment by twolfson** [comment]
Glad to hear it is properly sorted out now =)
