### ISSUE TITLE
Customize Class Name

### ISSUE THREAD

**Issue by undercloud** [twolfson/gulp.spritesmith#58]
How to remove or replace prefix ```.icon-``` ?

**Comment by twolfson** [comment]
You are looking for customizing the CSS selector. This can be done via `cssOpts.cssSelector`

https://github.com/twolfson/spritesheet-templates/tree/10.0.0#css

```js
spritesmith({
  // src, dest
  cssOpts: {
    cssSelector: function (sprite) {
      // Use sprite name as class (e.g. `home` -> `.home`)
      return '.' + sprite.name;
    }
  }
})
```

**Comment by undercloud** [comment]
thank you!))
