### ISSUE TITLE
spritesmith reduces a quality

### ISSUE THREAD

**Issue by yustnip** [twolfson/gulp.spritesmith#62]
After ```spritesmith``` a quality of images is reduced. For example:

- one of icons before: https://yadi.sk/i/A-2vCJkpihaqs
- after in the sprite: https://yadi.sk/i/4fUtiflYihasM

**Comment by twolfson** [comment]
I see some artifacts in the original image which is a JPG but don't see those artifacts in the spritesheet. What happens when you generate a spritesheet with only that 1 image?

P.S. I am going on vacation tomorrow for 2 weeks so I will likely be unresponsive after that. Other things to try: switching `spritesmith` engines.

**Comment by yustnip** [comment]
The sprite with from only 1 image: https://yadi.sk/i/JZg6Wrkqihbyg

I'll try to switch engines.

**Comment by twolfson** [comment]
What are the options you are passing to `gulp.spritesmith`?

**Comment by yustnip** [comment]
```
gulp.task('spritesmith', function() {
    var spriteData = gulp.src('./images/src/sprite/*.*').pipe(spritesmith({
        imgName: 'sprite.png',
        cssName: 'sprite.styl',
        cssFormat: 'stylus'
    }));
    spriteData.img.pipe(gulp.dest('./images/')); // путь, куда сохраняем картинку
    spriteData.css.pipe(gulp.dest('./styl/helpers/')); // путь, куда сохраняем стили
});
```

**Comment by twolfson** [comment]
It looks like the issue is being caused by loading from a JPG as the source image. There are a few options:

- Use a different engine (e.g. `gmsmith`)
- Lossless-ly convert source images to PNG (e.g. convert via ImageMagick/GraphicsMagick)
    - `for file in `ls`; do convert "$file" "$file.png"; done`

**Comment by yustnip** [comment]
Resaved images to .png. Now it's OK, thanks! Have a good vacations!

**Comment by twolfson** [comment]
That's great to hear. Thanks I will =)

**Comment by artem-malko** [comment]
Awesome :+1:
