### ISSUE TITLE
Parameters missing in scss

### ISSUE THREAD

**Issue by lbineau** [twolfson/gulp.spritesmith#66]
When I compile my spritesheet everything is going well but when I look in the scss generated it miss some parameters

```scss
$menu-dropdown: (0px, 0px, 0px, 0px, 9px, 5px, 9px, 5px, 'sprite.png', 'menu-dropdown', );
$menu-dropdown-2x: (0px, 0px, 0px, 0px, 18px, 10px, 18px, 10px, 'sprite@2x.png', 'menu-dropdown@2x', );

$spritesheet-sprites: ($menu-dropdown, );
$spritesheet: (9px, 5px, 'sprite.png', $spritesheet-sprites, );

$retina-spritesheet-sprites: ($menu-dropdown-2x, );
$retina-spritesheet: (18px, 10px, 'sprite@2x.png', $retina-spritesheet-sprites, );

$menu-dropdown-group: ('menu-dropdown', $menu-dropdown, $menu-dropdown-2x, );
$retina-groups: ($menu-dropdown-group, );
```
Does anyone have the same issue ?

**Comment by twolfson** [comment]
@lbineau Everything seems to be in order. The trailing commas are expected and due to using the `mustache` templating system. Are you having any issues generating sprites?

**Comment by lbineau** [comment]
@twolfson I found my mistake.
I was trying this :
```scss
@include sprite($menu-dropdown-group);
```
and I got the following error :
```
[gulp-sass] index out of bounds for `nth($list, $n)` on line 82 in *the path*
```
I thought that I have to use the group variable because it contains informations about retina and non retina, and the trailing commas make me think there was a mistake. I just used the wrong variable :
```scss
@include sprite($menu-dropdown);
```

**Comment by twolfson** [comment]
Ah, k. Yep, that should fix it. As a heads up, the `sprite` mixin is only for the normal variation of a sprite. If you want to get a retina sprite, the `retina-sprite` mixin should be used (which receives a group of normal and retina sprite information):

```
@include retina-sprite($menu-dropdown-group);
```
