### ISSUE TITLE
Retina clarity on mixin use

### ISSUE THREAD

**Issue by petulla** [twolfson/gulp.spritesmith#67]
In your examples, you use:

``@include retina-sprites($retina-groups);`

to somehow map the generated retina `sprite.scss` to a set of retina includes.

Which mixin is this or how does it work? I can't find this mixin and I'm not generating a set of retina sprites for my retina spritesheet, only the standard sizes. The scss output looks the same as if I weren't generating a retina sheet at all.

My task:

```
 var spriteData =
    gulp.src(config.paths.src.assets + '/sprites/*.*') //
            .pipe(spritesmith({
              retinaSrcFilter: [config.paths.src.assets + '/sprites/*@2x.png'],
                imgName: 'sprite.png',
                retinaImgName: 'sprite@2x.png',
                padding:1,
                cssName: '_sprite.scss',
                cssFormat: 'scss',
                algorithm: 'binary-tree
            }));
    spriteData.img.pipe(gulp.dest(config.paths.build.style)); //
    spriteData.css.pipe(gulp.dest(config.paths.src.style + '/sass')); //
```

Please help! I am in the final throes of a project.

**Comment by twolfson** [comment]
The root cause is by specifying `cssFormat: 'scss'`. This tells `spritesmith` to use the `scss` template which is built for normal sprites only. To remedy this, there are a few options:

- Remove `cssFormat` from options
    - By default, `spritesmith` will infer this based on the file extension (e.g. `_sprite.scss` -> `scss`)
- Change `cssFormat` to SCSS retina template
    - `cssFormat: 'scss_retina'`
