### ISSUE TITLE
Not picking up my @2x images

### ISSUE THREAD

**Issue by realchriswells** [twolfson/gulp.spritesmith#68]
I have followed the guide on creating retina sprites using gulp.spritesmith but I get this error:
```
AssertionError: Retina settings detected but 0 retina images were found. We have 4 normal images and expect these numbers to line up. Please double check `retinaSrcFilter`.
```

I have two sets of images in my images/icons-src folder:
Standard (64x64)
 - icon-twitter.png
 - icon-facebook.png

Retina (128x128)
 - icon-twitter@2x.png
 - icon-facebook@2x.png

My gulp task for it is:
```
gulp.task('sprites', function generateSpritesheets () {
    var spriteData = gulp.src('images/icons-src/*.png')
        .pipe(spritesmith({
            retinaSrcFilter: '*@2x.png',
            imgName: 'spritesheet.png',
            retinaImgName: 'spritesheet@2x.png',
            cssName: 'sprites.scss'
        }));

    spriteData.img
        .pipe(imagemin())
        .pipe(gulp.dest('images/dist/'));
    spriteData.css.pipe(gulp.dest('scss/icons/'));
});
```

If I remove the retinaSrcFilter and retinaImgName, a spritesheet gets created with all 4 images in it. The sprites.scss file also gets created correctly if the retina options are removed.

**Comment by petulla** [comment]
I think where you have retinaSrcFilter, the string should be: `images/icons-src/*@2x.png`

**Comment by realchriswells** [comment]
@petulla you are absolutely correct!

I thought that since it was generating the sprite sheet for the non-retina images that the filter would work from that piped information. Thank you so much!

**Comment by twolfson** [comment]
Based on the frequency of this issue, we should consider updating the error message to provide a suggestion about matching the initial glob =/ For example:

```
AssertionError: Retina settings detected but 0 retina images were found. Please make sure `retinaSrcFilter` is a similar pattern to the pattern passed to `gulp.src` (e.g. `gulp.src('path/to/images/*.png')`, `retinaSrcFilter: 'path/to/images/*@2x.png'`)
```

Going to reopen this as a reminder to ourselves.

**Comment by twolfson** [comment]
I forgot to close this but in `4.1.1`, we added a clarifying note in the README:

https://github.com/twolfson/gulp.spritesmith/compare/4.1.0...4.1.1
