### ISSUE TITLE
Padding on retina sprite images

### ISSUE THREAD

**Issue by petulla** [twolfson/gulp.spritesmith#69]
hi

I'm finding that the padding setting isn't working for retina sprites. Any advice?

**Comment by twolfson** [comment]
Can you provide an example?

**Comment by petulla** [comment]
Sure,

on the page, if I set padding on the sprite, I see: 
<img width="76" alt="screen shot 2015-09-28 at 6 25 23 pm" src="https://cloud.githubusercontent.com/assets/3466817/10150500/de1325ac-660d-11e5-84bb-badffe569d83.png">

This is odd. The sprite itself has padding:
<img width="271" alt="screen shot 2015-09-28 at 6 25 30 pm" src="https://cloud.githubusercontent.com/assets/3466817/10150507/e607a1b6-660d-11e5-86ed-3dd1b7967b02.png">

How do I reconcile what I'm seeing on the page (a sprite with extra padding) vs. the sprite itself?

**Comment by twolfson** [comment]
Can you paste the `gulp.src` and configuration you are using?

**Comment by petulla** [comment]
```
 var spriteData =
    gulp.src(config.paths.src.assets + '/sprites/*.*') //
            .pipe(spritesmith({
              retinaSrcFilter: [config.paths.src.assets + '/sprites/*@2x.png'],
                padding:3,
                imgName: 'sprite.png',
                retinaImgName: 'sprite@2x.png',
                cssName: '_sprite.scss',
                cssFormat: 'scss_retina',
                algorithm: 'binary-tree'
            }));
    spriteData.img.pipe(gulp.dest(config.paths.build.style)); //
    spriteData.css.pipe(gulp.dest(config.paths.src.style + '/sass')); //

```

**Comment by petulla** [comment]
I find the on the page vs. the sprite behavior odd.. thoughts?

**Comment by twolfson** [comment]
Everything looks like it should work. From the fragmented screenshots of the spritesheets, it looks like the sprites were loaded out of order though. Any idea why that would be?

**Comment by petulla** [comment]
It appears as though the background is repeating..

**Comment by twolfson** [comment]
We only pad between sprites -- the edge padding wouldn't make sense as it's built to remove bleeding due to browser scaling (Ensighten/spritesmith#7)

https://github.com/Ensighten/spritesmith/blob/1.4.0/src/smith.js#L77-L82

https://github.com/Ensighten/spritesmith/blob/1.4.0/src/smith.js#L120-L126

**Comment by petulla** [comment]
I needed to add the padding manually to the retina mixin to solve the problem. I also needed to prevent background-repeat to eliminate the duplication issue.

**Comment by twolfson** [comment]
Not sure what you mean by that since we double padding for retina spritesheets =/

https://github.com/twolfson/gulp.spritesmith/blob/4.1.1/lib/gulp-spritesmith.js#L188

But in any case, I am glad your issue is resolved =)
