### ISSUE TITLE
Using @include retina-sprite results in "index out of bounds for `nth($list, $n)`"

### ISSUE THREAD

**Issue by OliverJEvans** [twolfson/gulp.spritesmith#71]
Hello,

I know you've got a few other issues related to this error message that have either been resolved or 'wontfix' due to out of date versions of dependancies but as fair as I'm aware everything I'm using is up to date. 

I've made a [stripped down repo](https://github.com/OliverJEvans/spritesmith-issue-2) to show you how I've it everything setup but will post code in the issue so if the repo is removed, everyone still has something to reference.

So i'm using SCSS and heres my gulp file. 

```javascript
var gulp = require('gulp');
var spritesmith = require('gulp.spritesmith');

gulp.task('sprite', function () {
	var spriteData = gulp.src('src/images/*.png').pipe(spritesmith({
		imgName: 'images/sprite.png',
		cssName: 'css/_sprite.scss',
		retinaSrcFilter: ['src/images/*@2x.png'],
		retinaImgName: 'images/sprite@2x.png',
	}));
	spriteData.pipe(gulp.dest('src/'));
});

var sass = require('gulp-sass');
 
gulp.task('sass', function () {
  gulp.src('src/css/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('dist/css'));
});
 
gulp.task('sass:watch', function () {
  gulp.watch('src/css/**/*.scss', ['sass']);
});
```

The `gulp sprite` command works like a charm. No issues there. Its when I run `gulp sass` I get the following error message:

```
[08:49:29] Using gulpfile ~/Documents/workspace/spritesmith-issue-2/gulpfile.js
[08:49:29] Starting 'sass'...
[08:49:29] Finished 'sass' after 7.65 ms
Error in plugin 'sass'
Message:
    src/css/_sprite.scss
  106:18  index out of bounds for `nth($list, $n)`
 ```

Here is the mixin it is failing on:

```css
@mixin sprite-image($sprite) {
  $sprite-image: nth($sprite, 9); /*line: 106*/
  background-image: url(#{$sprite-image});
}
```

So what versions of stuff am I running?

* Sass 3.4.16 (Selective Steve)
* gulp-sass@2.0.4 
* node-sass@3.3.3

Do you have any ideas please?

Thanks in advance

**Comment by twolfson** [comment]
Wow, thanks for all the effort put into this issue!

Unfortunately, the problem is due to using the wrong variable. `retina_sprite` expects a `$retina-sprite-group` variable but it was getting a `$sprite` variable:

https://github.com/OliverJEvans/spritesmith-issue-2/blob/6a56d147156b2aed0e0986766bd7a0b6abca910f/src/css/_sprite.scss#L126

https://github.com/OliverJEvans/spritesmith-issue-2/blob/6a56d147156b2aed0e0986766bd7a0b6abca910f/src/css/_screen.scss#L2

If we use `$icon-group` instead of `$icon`, then the issue should go away:

```
@include retina-sprite($icon-group);
```

**Comment by OliverJEvans** [comment]
Wow rapid reply, perfect thank you.
Keep up the good work :)

**Comment by Santoshah** [comment]
@twolfson Great thanks :)
