### ISSUE TITLE
Error handling.

### ISSUE THREAD

**Issue by webDevRN** [twolfson/gulp.spritesmith#73]
The project I am working on is getting larger and there have been times when multiple people have added new images to be run through spritesmith at the same time. If one of those images are named incorrectly or left out we get is the generic error from the code below. Is it possible to emit an error event instead of using assert? This would allow me to add a custom error details to my log. I could then display which folder and image type is causing the issue.

Also note number 6 on https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md 

// If we have a different amount of normal and retina images, complain and leave
      assert(images.length === retinaImages.length,
        'Retina settings detected but ' + retinaImages.length + ' retina images were found. ' +
        'We have ' + images.length + ' normal images and expect these numbers to line up. ' +
        'Please double check `retinaSrcFilter`.');

**Comment by webDevRN** [comment]
What I am really looking for is the folder and the image type that caused the issue. The imgName var seems to have all that information on it, but is not being logged.

**Comment by twolfson** [comment]
Ah, I think we didn't fully think that through when porting from `grunt-spritesmith`. That's definitely a reasonable request.

Part of me wants to provide the full JSON forms of images but I think that will get overwhelming for people with 50+ sprites =/

How does emitting an error with an `images` and `retinaImages` property sound? (where `images` is the array of vinyl-fs objects resolved)

**Comment by webDevRN** [comment]
That would be great. Thank you.

**Comment by twolfson** [comment]
This has been patched/released in `4.2.0`. Thanks for the bug report and correcting our behavior =)
