### ISSUE TITLE
can't  rename css selector

### ISSUE THREAD

**Issue by synchronizingtheworld** [twolfson/gulp.spritesmith#74]
example:
.icon-sort {
  background-image: url(sprite.png);
  background-position: -493px -273px;
  width: 24px;
  height: 20px;
}

'icon-' prefix  me   Cannot modify  ?

**Comment by twolfson** [comment]
This is a duplicate issue from #51 and #58. You can adjust the `cssSelector` via `cssOpts.cssSelector`. Here is an example:

```js
cssOpts: {
  cssSelector: function (sprite) {
    // Use sprite name as its own selector (e.g. `sort` -> `.sort`)
    return '.' + sprite.name;
  }
}
```

**Comment by synchronizingtheworld** [comment]
thanks
