### ISSUE TITLE
Retina rules less no dot mix-in inside another mediaQuery

### ISSUE THREAD

**Issue by mihai-coanda** [twolfson/gulp.spritesmith#79]
@media screen {
  .myclass {
    .retina-sprite(@-my-icon-group);
  }
}

when compiling the less i obtain : 
.myclass {
    background-image: url(../images/icons-sprite.png);
    background-position: -89px -88px;
    width: 16px;
    height: 16px
}

But the retina rules are not compiled

**Comment by twolfson** [comment]
It looks like that should work. I have a feeling this is due to nested media queries. Can you verify that the following code compiles in your LESS?

```
@media screen {
  .hello {
     color: blue; 
  }
  
  @media (-webkit-min-device-pixel-ratio: 2),
         (min-resolution: 192dpi) {
    .hello {
      color: red; 
    }
  }
}
```

**Comment by mihai-coanda** [comment]
it compiles fine.
@media only screen {
  .hello {
    color: #00f
  }
}

@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi) {
  .hello {
    color: red
  }
}

**Comment by twolfson** [comment]
Can you paste the entire LESS output from spritesmith into a gist (gist.github.com) or pastebin?

**Comment by mihai-coanda** [comment]
I have an very large project and the less output is 4000 lines.
My css rule : 
@media only screen {
  /**
   * Icons representing the problem severity.
   */
  .validation-item[data-severity="error"] > .validation-problem-wrapper:before {
    display: block;
    content: "";
    .retina-sprite(@-error16-group);
  }
}

My output on this class retina:
@media only screen and only screen and (-webkit-min-device-pixel-ratio:

1.3),only screen and only screen and

(min--moz-device-pixel-ratio:

1.3),only screen and only screen and

(-webkit-min-device-pixel-ratio:

130),only screen and only screen and

(min-resolution:

130dppx

) {
  .validation-item[data-severity=error] > .validation-problem-wrapper:before {
    background-image: url(../images/icons-sprite@2x.png);
    background-size: 261px 141px
  }
}

Custom retina condiion in template : 
@media only screen and (-webkit-min-device-pixel-ratio: 1.3),
       only screen and (min--moz-device-pixel-ratio: 1.3),
       only screen and (min-resolution: 130dppx) {
    .sprite-image(@retina-sprite);
    .sprite-background-size(@normal-sprite);
  }

**Comment by twolfson** [comment]
I don't understand. Are you using a template that isn't built into `gulp.spritesmith`?

**Comment by mihai-coanda** [comment]
yes, sorry i forgot to say that but i do not think that my rule is the one responsible for this.
The problem seem to to be that it generates retina rules but it generates them with "@media only screen and only screen [pixel-ratio-condition] ", the "screen and screen" rule seems to be valid but always be false.
I do not know all the technologies involved and if this can be filtered out.

**Comment by twolfson** [comment]
Can you paste the template you are using into a gist or pastebin?

**Comment by mihai-coanda** [comment]
Shure
http://pastebin.com/aFmS8dG9

**Comment by twolfson** [comment]
Everything looks fine in the template. Upon re-reading the CSS output (https://github.com/twolfson/gulp.spritesmith/issues/79#issuecomment-165697957), you are saying that the retina CSS is getting output so I don't understand what the issue is =/

**Comment by twolfson** [comment]
Closing issue due to 1 month of inactivity
