### ISSUE TITLE
when set the padding,  want to put the padding in the outermost sprite

### ISSUE THREAD

**Issue by hitima** [twolfson/gulp.spritesmith#81]
used with the zoom, 
the end of the other image displayed.（By the scale factor）

**Comment by twolfson** [comment]
In that scenario, I would recommend setting `background-repeat: no-repeat` for all of your sprites as it will save on bandwidth when combined with `gzip`.

To set that for all of your sprites, if we are using the CSS template, then we will need to define a custom template. We can leverage inheritance to keep it as simple as possible:

https://github.com/twolfson/gulp.spritesmith/tree/6.0.1#handlebars-inheritance

We will inherit from: https://github.com/twolfson/spritesheet-templates/blob/10.0.0/lib/templates/css.template.handlebars

**css.template.handlebars:**

```
{{#extend "css"}}
{{#block "sprites"}}
{{#each sprites}}
{{{selector}}} {
  background-image: url({{{escaped_image}}});
  background-position: {{px.offset_x}} {{px.offset_y}};
  width: {{px.width}};
  height: {{px.height}};
  background-repeat: no-repeat;
}
{{/each}}
{{/block}}
```

If we are using a templating language like SCSS, then we can either do inheritance similar to the above or override the `sprite` mixin with a new property:

Reference code: https://github.com/twolfson/spritesheet-templates/blob/10.0.0/lib/templates/scss.template.handlebars#L81-L86

```
// Import our variables and mixins generated by spritesmith
@import "spritesmith-output";

// Override our sprite mixin
@mixin sprite($sprite) {
  @include sprite-image($sprite);
  @include sprite-position($sprite);
  @include sprite-width($sprite);
  @include sprite-height($sprite);
  background-repeat: no-repeat;
}

// Call our sprite mixin
@include sprite($icon-home);
```
