### ISSUE TITLE
Can I change image size as half ?

### ISSUE THREAD

**Issue by Taewa** [twolfson/gulp.spritesmith#82]
Hello. Thanks for awesome plugin, it will save my time a lot.

By the way I am wondering if I can change the size of each image.

For example, let's say original image is 100*100. Then gulp.spritesmith will generates css as
```
.icon-img {
    background-image: url(../img/sprite.png);
    background-position: -210px -82px;
    width: 100px;
    height: 100px;
}
```

I want this to make as half size (eg : width : 50px, height : 50px). half size image makes better view for mobile web.
To make this 
`background-size` must be half.
`background-position`, `width`, `height` as well.

I check the retina part but it seems I have to prepare at least 2 pair of images. Just I want to use 1 image.

How can I resolve my problem?

Thank you.

**Comment by twolfson** [comment]
We prefer to keep resizing logic outside of `gulp.spritesmith` as there are a lot of ways to handle sampling. Instead, we suggest using a `gulp` plugin to prepare images before running `gulp.spritesmith`. For example:

https://www.npmjs.com/package/gulp-image-resize/

To use that in a Gulpfile, we would define a separate task and set it as a dependency of `sprite`:

```js
// Load in our dependencies
var gulp = require('gulp');
var imageResize = require('gulp-image-resize');
var spritesmith = require('gulp.spritesmith');

// Define our gulp tasks
gulp.task('downsize-retina-sprites', function downsizeRetinaSprites () {
  return gulp.src('path/to/sprites-2x/*.png')
    .pipe(imageResize({width: '50%', height: '50%'})
    .pipe(gulp.dest('path/to/sprites-1x'));
});

gulp.task('sprite', ['downsize-retina-sprites'], function generateSprites () {
  return gulp.src(['path/to/sprites-1x/*.png', 'path/to/sprites-2x/*.png'])
    .pipe(spritesmith({
      retinaSrcFilter: ['path/to/sprites-1x/*.png'],
      imgName: 'sprite.png',
      retinaImgName: 'sprite@2x.png',
      cssName: 'sprite.css'
    })
    .pipe(gulp.dest('dist'));
});
```
