### ISSUE TITLE
CSS output

### ISSUE THREAD

**Issue by witoldszpur** [twolfson/gulp.spritesmith#83]
CSS/SCSS should contain one main **.class** where is **{{url}}** , because now **url** duplicate in each class name and make finale .css file much bigger. I know that I can create my template but this should be  by default, because 100 icon make 100xURL.

**Comment by twolfson** [comment]
When we discuss consolidating lines for CSS rules, we start talking about CSS optimization which is outside of the scope of this project.

We recommend using a tool like `csso` after the sprite rules are generated. An example can be found in the README:

https://github.com/twolfson/gulp.spritesmith/tree/6.2.0#continuing-the-pipeline

Package: https://github.com/ben-eb/gulp-csso
