### ISSUE TITLE
Improve option cssTemplate or add new

### ISSUE THREAD

**Issue by rorc** [twolfson/gulp.spritesmith#86]
Hello!

How i can use different handlebars templates for different images?

I want something like this:

```javascript
spritesmith({
    cssTemplate: function(sprite) {
        if (sprite.foldername == 'contacts') {
            return 'assets/sprite-contacts.css.handlebars';
        }
        return 'assets/sprite.css.handlebars';
    }
})
```

**Comment by twolfson** [comment]
`spritesmith` only outputs 1 CSS file for a task as we assume the sprites are related. For your scenario, I would suggest:

- Output CSS preprocessor variables (e.g. SCSS, LESS, Stylus) and compile separate CSS files from those variables

On a separate note, we want to better understand how `spritesmith` is being used. Can you explain why you need multiple CSS files?

**Comment by rorc** [comment]
Ok, sigh.., thanks, i will use SASS variables.
I dont need multiple CSS files, i need to get different CSS classes for different images without manual intervention through variables, e.i:
for images in folder "contacts" i want CSS rule:
```
{{#sprites}}
.icon-{{name}}:before {
    content: '';
    width: {{px.width}};
    height: {{px.height}};
    display: inline-block;
    vertical-align: middle;
    background: url({{{escaped_image}}}) {{px.offset_x}} {{px.offset_y}};
}
{{/sprites}}
```
Etc..
And for default icons:
```
{{#sprites}}
.icon-{{name}} {
    width: {{px.width}};
    height: {{px.height}};
    background: url({{{escaped_image}}}) {{px.offset_x}} {{px.offset_y}};
}
{{/sprites}}
```

**Comment by twolfson** [comment]
Ah, k. In that scenario you can:

- Define a property on each sprite via `cssVarMap` and use a custom template:

**spritesmith params:**

```js
cssVarMap: function (sprite) {
  sprite.is_contact_sprite = sprite.image.indexOf('contacts') !== -1;
}
```

**Custom template:**

```
{{#each sprites}}
{{#if is_contact_sprite}}
  // Contact sprite CSS goes here
{{#else}}
  // Normal sprite CSS goes here
{{/if}}
{{/each}}
```

- Register a new handlebars helper to faciliate the `foldername` and use that in the template

- Use a more powerful templating language as your CSS template (e.g. EJS) which will allow you to perform conditionals on sprite paths
    - Reference example: https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#template-function

**spritesmith params:**

```js
spritesmith({
    cssTemplate: ejs.compile(templateStr)
})
```

**Custom template:**

```ejs
<% sprites.forEach(function (sprite) { %>
  <% if (sprite.indexOf('contacts') !== -1) { %>
    // Contact sprite CSS goes here
 <% } else { %>
    // Normal sprite CSS goes here
  <% } %>
<% }); %>
```

**Comment by rorc** [comment]
Oh, big ty for detailed answer :)
First example is more correct i think.
And why I did not guess...
