### ISSUE TITLE
index out of bounds for `nth($list, $n)`

### ISSUE THREAD

**Issue by CreativeZoller** [twolfson/gulp.spritesmith#89]
I just updated my packages and now my task dies. I have retina images in images/sprites2x with name XY.png and XY@2x.png. Spritesmith generates the sass-file but gulp-sass won't compile according to error message:
```
gulp-notify: [sassCompile error!] .tmp/scss/retinaSprites.scss
Error: index out of bounds for `nth($list, $n)` on line 175 of .tmp/scss/retinaSprites.scss >>   $normal-sprite: nth($retina-group, 2);
```

Which row is in this auto-generated mixin:
```
@mixin retina-sprite($retina-group) {
  $normal-sprite: nth($retina-group, 2);
  $retina-sprite: nth($retina-group, 3);
  @include sprite($normal-sprite);
  @media (-webkit-min-device-pixel-ratio: 2),
         (min-resolution: 192dpi) {
    @include sprite-image($retina-sprite);
    @include sprite-background-size($normal-sprite);
  }
}
```

Of course it only happens when I'm trying to include it to my style declarations as suggested:
`  &-fork {
    @include retina-sprites($fork-group);
  }`

I am using these right now:
"node": " v5.6.0 ",
"gulp": "^3.9.1",
"gulp.spritesmith": "^6.2.1",
"gulp-sass": "^2.3.1"

Thanks for any reply in advance.

**Comment by twolfson** [comment]
It looks like you have a typo; you are using the mixin for a list of retina groups on a single retina group (i.e. `retina-sprites` on `$fork-group`). Try out the following:

```scss
 &-fork { @include retina-sprite($fork-group); }
```
