### ISSUE TITLE
Max-(width/height) sprite

### ISSUE THREAD

**Issue by SvBoxel** [twolfson/gulp.spritesmith#91]
Is there any possibility assign a max-width to the sprite? Now it always tries to be a square with the default algorithm. Using the topdown algorithm makes is just really long. 
What I like to achieve is that the sprite has a max-width of let's say 200px and can be as long as it needs to be to fit all the icons.

**Comment by twolfson** [comment]
With our built-in algorithms, there isn't any way to limit dimensions. However, our library does support adding custom algorithms; see this issue's code sample as an example:

https://github.com/twolfson/layout/issues/9#issuecomment-219883451

For references as to what a layout algorithm looks like, please see the following files:

https://github.com/twolfson/layout/tree/2.2.0/lib/algorithms
