### ISSUE TITLE
Multiple sprites in one project? 

### ISSUE THREAD

**Issue by inferusvv** [twolfson/gulp.spritesmith#92]
Is there any way to use this module and generate multiple sprites? Now in 2 SCSS files i have similar variables, like `$spritesheet-sprites` for examples

**Comment by twolfson** [comment]
Variable names can be changed via parameters like `cssVarMap` and `cssSpritesheetName`. Here's example code from a test:

https://github.com/twolfson/gulp.spritesmith/blob/6.2.1/test/gulpfile.js#L97-L106

https://github.com/twolfson/gulp.spritesmith/blob/6.2.1/test/expected-files/spritesheet-name/sprite.scss#L47-L51
