### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by lexmills** [twolfson/gulp.spritesmith#94]
Error: There are some read requests waitng on finished stream at ChunckStream._end

Could someone help me with this issue?

**Comment by twolfson** [comment]
Could you post your gulpfile?

**Comment by lexmills** [comment]
var gulp = require('gulp'),
  sass = require('gulp-sass'),
  spritesmith = require('gulp.spritesmith');

gulp.task('sass', function() {
  return gulp.src('sass/*.scss')
    .pipe(sass())
    .pipe(gulp.dest('css/'))
});

gulp.task('sprite', function() {
  var spriteData = gulp.src('images/*.png')
    .pipe(spritesmith({
        imgName: 'sprite.png',
        cssName: 'sprite.css'
    }));
    spriteData.img.pipe(gulp.dest('images'));
    spriteData.css.pipe(gulp.dest('css'));
});

gulp.task('watch', function() {
  gulp.watch('sass/*.scss', ['sass']);
  gulp.watch('images/*.png', ['sprite']);
});

**Comment by twolfson** [comment]
You aren't returning nor calling back from the `gulp` task so `gulp` is assuming the task was synchronous. Please see the README for an example.

https://github.com/twolfson/gulp.spritesmith/tree/6.2.1#continuing-the-pipeline

**Comment by lexmills** [comment]
Is there a reason it was working before, I didn't change any of the code, and it suddenly stopped working?  

I have updated my gulp file to be exactly like in the readme (with correct updates to paths), but am still getting the same error. 

I tried finding someone with the same issue, but couldn't, or else I would not bother you.  Just trying to understand.
