### ISSUE TITLE
event.js:141 throw er; // unhandled 'error' event ; I got this error while trying to run gulp tasks, http://prntscr.com/bxrf51  , Thank you for any help! 

### ISSUE THREAD

**Issue by SaidV12** [twolfson/gulp.spritesmith#96]

**Comment by twolfson** [comment]
This means that the Node.js process ran out of memory, this typically means the machine lacks sufficient memory to build spritesheets. This can possibly mean;

- Images going into spritesheet are too large
- Machine doesn't have a lot of memory (e.g. 512MB might not be enough)

**Comment by SaidV12** [comment]
Thank you @twolfson .
